// Code generated by ent, DO NOT EDIT.

package relaysitemodelprice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldDeletedAt, v))
}

// RelaySiteID applies equality check predicate on the "relay_site_id" field. It's identical to RelaySiteIDEQ.
func RelaySiteID(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldRelaySiteID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldModelID, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLTE(FieldDeletedAt, v))
}

// RelaySiteIDEQ applies the EQ predicate on the "relay_site_id" field.
func RelaySiteIDEQ(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldRelaySiteID, v))
}

// RelaySiteIDNEQ applies the NEQ predicate on the "relay_site_id" field.
func RelaySiteIDNEQ(v int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNEQ(FieldRelaySiteID, v))
}

// RelaySiteIDIn applies the In predicate on the "relay_site_id" field.
func RelaySiteIDIn(vs ...int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIn(FieldRelaySiteID, vs...))
}

// RelaySiteIDNotIn applies the NotIn predicate on the "relay_site_id" field.
func RelaySiteIDNotIn(vs ...int) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotIn(FieldRelaySiteID, vs...))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldContainsFold(FieldModelID, v))
}

// PriceIsNil applies the IsNil predicate on the "price" field.
func PriceIsNil() predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIsNull(FieldPrice))
}

// PriceNotNil applies the NotNil predicate on the "price" field.
func PriceNotNil() predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotNull(FieldPrice))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.FieldLTE(FieldSyncedAt, v))
}

// HasRelaySite applies the HasEdge predicate on the "relay_site" edge.
func HasRelaySite() predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RelaySiteTable, RelaySiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelaySiteWith applies the HasEdge predicate on the "relay_site" edge with a given conditions (other predicates).
func HasRelaySiteWith(preds ...predicate.RelaySite) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(func(s *sql.Selector) {
		step := newRelaySiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelaySiteModelPrice) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelaySiteModelPrice) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelaySiteModelPrice) predicate.RelaySiteModelPrice {
	return predicate.RelaySiteModelPrice(sql.NotPredicates(p))
}
