// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"user", "service_account", "noauth", "personal"}, Default: "user"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "enabled"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "profiles", Type: field.TypeJSON, Nullable: true},
		{Name: "allowed_ips", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_projects_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[11]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "api_keys_by_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[12]},
			},
			{
				Name:    "api_keys_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[11]},
			},
			{
				Name:    "api_keys_by_key",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
		},
	}
	// APIKeyProfileTemplatesColumns holds the columns for the "api_key_profile_templates" table.
	APIKeyProfileTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "profile", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt},
	}
	// APIKeyProfileTemplatesTable holds the schema information for the "api_key_profile_templates" table.
	APIKeyProfileTemplatesTable = &schema.Table{
		Name:       "api_key_profile_templates",
		Columns:    APIKeyProfileTemplatesColumns,
		PrimaryKey: []*schema.Column{APIKeyProfileTemplatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_key_profile_templates_projects_api_key_profile_templates",
				Columns:    []*schema.Column{APIKeyProfileTemplatesColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "api_key_profile_templates_by_project_name",
				Unique:  true,
				Columns: []*schema.Column{APIKeyProfileTemplatesColumns[7], APIKeyProfileTemplatesColumns[4], APIKeyProfileTemplatesColumns[3]},
			},
		},
	}
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"openai", "openai_responses", "atlascloud", "cline", "codex", "vercel", "anthropic", "anthropic_aws", "anthropic_gcp", "gemini_openai", "gemini", "gemini_vertex", "deepseek", "deepseek_anthropic", "deepinfra", "qiniu", "fireworks", "doubao", "doubao_anthropic", "moonshot", "moonshot_anthropic", "zhipu", "zai", "zhipu_anthropic", "zai_anthropic", "anthropic_fake", "openai_fake", "openrouter", "xiaomi", "xiaomi_anthropic", "xai", "xai_responses", "xai_subscription", "ppio", "siliconflow", "volcengine", "volcengine_anthropic", "longcat", "longcat_anthropic", "minimax", "minimax_anthropic", "aihubmix", "aihubmix_anthropic", "burncloud", "modelscope", "bailian", "bailian_anthropic", "moonshot_coding", "jina", "github", "github_copilot", "claudecode", "cerebras", "antigravity", "nanogpt", "nanogpt_responses", "opencode_go", "opencode_go_anthropic", "ollama", "ollama_anthropic", "evolink", "evolink_anthropic", "groq", "qiniu_anthropic", "fenno"}},
		{Name: "base_url", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "credentials", Type: field.TypeJSON},
		{Name: "disabled_api_keys", Type: field.TypeJSON, Nullable: true},
		{Name: "supported_models", Type: field.TypeJSON},
		{Name: "manual_models", Type: field.TypeJSON, Nullable: true},
		{Name: "auto_sync_supported_models", Type: field.TypeBool, Default: false},
		{Name: "auto_sync_model_pattern", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "default_test_model", Type: field.TypeString},
		{Name: "policies", Type: field.TypeJSON, Nullable: true},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "ordering_weight", Type: field.TypeInt, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "auto_disabled_at", Type: field.TypeTime, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "endpoints", Type: field.TypeJSON, Nullable: true},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "channels_by_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelsColumns[6], ChannelsColumns[3]},
			},
		},
	}
	// ChannelModelPricesColumns holds the columns for the "channel_model_prices" table.
	ChannelModelPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "model_id", Type: field.TypeString},
		{Name: "price", Type: field.TypeJSON},
		{Name: "reference_id", Type: field.TypeString, Unique: true},
		{Name: "channel_id", Type: field.TypeInt},
	}
	// ChannelModelPricesTable holds the schema information for the "channel_model_prices" table.
	ChannelModelPricesTable = &schema.Table{
		Name:       "channel_model_prices",
		Columns:    ChannelModelPricesColumns,
		PrimaryKey: []*schema.Column{ChannelModelPricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_model_prices_channels_channel_model_prices",
				Columns:    []*schema.Column{ChannelModelPricesColumns[7]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_model_prices_by_channel_id_model_id",
				Unique:  true,
				Columns: []*schema.Column{ChannelModelPricesColumns[7], ChannelModelPricesColumns[4], ChannelModelPricesColumns[3]},
			},
		},
	}
	// ChannelModelPriceVersionsColumns holds the columns for the "channel_model_price_versions" table.
	ChannelModelPriceVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "model_id", Type: field.TypeString},
		{Name: "price", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}},
		{Name: "effective_start_at", Type: field.TypeTime},
		{Name: "effective_end_at", Type: field.TypeTime, Nullable: true},
		{Name: "reference_id", Type: field.TypeString, Unique: true},
		{Name: "channel_model_price_id", Type: field.TypeInt},
	}
	// ChannelModelPriceVersionsTable holds the schema information for the "channel_model_price_versions" table.
	ChannelModelPriceVersionsTable = &schema.Table{
		Name:       "channel_model_price_versions",
		Columns:    ChannelModelPriceVersionsColumns,
		PrimaryKey: []*schema.Column{ChannelModelPriceVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_model_price_versions_channel_model_prices_versions",
				Columns:    []*schema.Column{ChannelModelPriceVersionsColumns[10]},
				RefColumns: []*schema.Column{ChannelModelPricesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ChannelOverrideTemplatesColumns holds the columns for the "channel_override_templates" table.
	ChannelOverrideTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "override_parameters", Type: field.TypeString},
		{Name: "override_headers", Type: field.TypeJSON},
		{Name: "header_override_operations", Type: field.TypeJSON, Nullable: true},
		{Name: "body_override_operations", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// ChannelOverrideTemplatesTable holds the schema information for the "channel_override_templates" table.
	ChannelOverrideTemplatesTable = &schema.Table{
		Name:       "channel_override_templates",
		Columns:    ChannelOverrideTemplatesColumns,
		PrimaryKey: []*schema.Column{ChannelOverrideTemplatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_override_templates_users_channel_override_templates",
				Columns:    []*schema.Column{ChannelOverrideTemplatesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_override_templates_by_user_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelOverrideTemplatesColumns[10], ChannelOverrideTemplatesColumns[4], ChannelOverrideTemplatesColumns[3]},
			},
		},
	}
	// ChannelProbesColumns holds the columns for the "channel_probes" table.
	ChannelProbesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "total_request_count", Type: field.TypeInt},
		{Name: "success_request_count", Type: field.TypeInt},
		{Name: "avg_tokens_per_second", Type: field.TypeFloat64, Nullable: true},
		{Name: "avg_time_to_first_token_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "timestamp", Type: field.TypeInt64},
		{Name: "channel_id", Type: field.TypeInt},
	}
	// ChannelProbesTable holds the schema information for the "channel_probes" table.
	ChannelProbesTable = &schema.Table{
		Name:       "channel_probes",
		Columns:    ChannelProbesColumns,
		PrimaryKey: []*schema.Column{ChannelProbesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_probes_channels_channel_probes",
				Columns:    []*schema.Column{ChannelProbesColumns[6]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_probes_by_channel_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{ChannelProbesColumns[6], ChannelProbesColumns[5]},
			},
		},
	}
	// DataStoragesColumns holds the columns for the "data_storages" table.
	DataStoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "primary", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"database", "fs", "s3", "gcs", "webdav"}},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
	}
	// DataStoragesTable holds the schema information for the "data_storages" table.
	DataStoragesTable = &schema.Table{
		Name:       "data_storages",
		Columns:    DataStoragesColumns,
		PrimaryKey: []*schema.Column{DataStoragesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "data_sources_by_name",
				Unique:  true,
				Columns: []*schema.Column{DataStoragesColumns[4]},
			},
		},
	}
	// InvitationsColumns holds the columns for the "invitations" table.
	InvitationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "role_id", Type: field.TypeInt, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "max_uses", Type: field.TypeInt, Default: 1},
		{Name: "used_count", Type: field.TypeInt, Default: 0},
		{Name: "project_id", Type: field.TypeInt},
	}
	// InvitationsTable holds the schema information for the "invitations" table.
	InvitationsTable = &schema.Table{
		Name:       "invitations",
		Columns:    InvitationsColumns,
		PrimaryKey: []*schema.Column{InvitationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invitations_projects_invitations",
				Columns:    []*schema.Column{InvitationsColumns[9]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invitation_token_hash",
				Unique:  true,
				Columns: []*schema.Column{InvitationsColumns[4]},
			},
			{
				Name:    "invitation_project_id",
				Unique:  false,
				Columns: []*schema.Column{InvitationsColumns[9]},
			},
		},
	}
	// ModelsColumns holds the columns for the "models" table.
	ModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "developer", Type: field.TypeString},
		{Name: "model_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"chat", "embedding", "rerank", "image_generation", "video_generation"}, Default: "chat"},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
		{Name: "group", Type: field.TypeString},
		{Name: "model_card", Type: field.TypeJSON},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// ModelsTable holds the schema information for the "models" table.
	ModelsTable = &schema.Table{
		Name:       "models",
		Columns:    ModelsColumns,
		PrimaryKey: []*schema.Column{ModelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "models_by_name",
				Unique:  true,
				Columns: []*schema.Column{ModelsColumns[7], ModelsColumns[3]},
			},
			{
				Name:    "models_by_model_id",
				Unique:  true,
				Columns: []*schema.Column{ModelsColumns[5], ModelsColumns[3]},
			},
		},
	}
	// OidcIdentitiesColumns holds the columns for the "oidc_identities" table.
	OidcIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "issuer", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "idp_name", Type: field.TypeString, Nullable: true},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// OidcIdentitiesTable holds the schema information for the "oidc_identities" table.
	OidcIdentitiesTable = &schema.Table{
		Name:       "oidc_identities",
		Columns:    OidcIdentitiesColumns,
		PrimaryKey: []*schema.Column{OidcIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "oidc_identities_users_user",
				Columns:    []*schema.Column{OidcIdentitiesColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "oidc_identities_by_issuer_subject_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{OidcIdentitiesColumns[4], OidcIdentitiesColumns[5], OidcIdentitiesColumns[3]},
			},
			{
				Name:    "oidc_identities_by_user_id",
				Unique:  false,
				Columns: []*schema.Column{OidcIdentitiesColumns[9]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
		{Name: "profiles", Type: field.TypeJSON, Nullable: true},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "projects_by_name",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[4], ProjectsColumns[3]},
			},
		},
	}
	// PromptsColumns holds the columns for the "prompts" table.
	PromptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "role", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, SchemaType: map[string]string{"mysql": "longtext"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled"}, Default: "disabled"},
		{Name: "order", Type: field.TypeInt, Default: 0},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "project_id", Type: field.TypeInt},
	}
	// PromptsTable holds the schema information for the "prompts" table.
	PromptsTable = &schema.Table{
		Name:       "prompts",
		Columns:    PromptsColumns,
		PrimaryKey: []*schema.Column{PromptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "prompts_projects_prompts",
				Columns:    []*schema.Column{PromptsColumns[11]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "prompts_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{PromptsColumns[11]},
			},
			{
				Name:    "prompts_by_project_id_name",
				Unique:  true,
				Columns: []*schema.Column{PromptsColumns[11], PromptsColumns[4], PromptsColumns[3]},
			},
		},
	}
	// PromptProtectionRulesColumns holds the columns for the "prompt_protection_rules" table.
	PromptProtectionRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "pattern", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "settings", Type: field.TypeJSON},
	}
	// PromptProtectionRulesTable holds the schema information for the "prompt_protection_rules" table.
	PromptProtectionRulesTable = &schema.Table{
		Name:       "prompt_protection_rules",
		Columns:    PromptProtectionRulesColumns,
		PrimaryKey: []*schema.Column{PromptProtectionRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "prompt_protection_rules_by_name",
				Unique:  true,
				Columns: []*schema.Column{PromptProtectionRulesColumns[4], PromptProtectionRulesColumns[3]},
			},
		},
	}
	// ProviderQuotaStatusColumns holds the columns for the "provider_quota_status" table.
	ProviderQuotaStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "provider_type", Type: field.TypeEnum, Enums: []string{"claudecode", "codex", "xai_subscription", "github_copilot", "nanogpt", "cline", "wafer", "synthetic", "neuralwatt", "apertis", "opencode_go", "kimi_code", "minimax", "zhipu", "charm_hyper"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"available", "warning", "exhausted", "unknown"}},
		{Name: "quota_data", Type: field.TypeJSON},
		{Name: "next_reset_at", Type: field.TypeTime, Nullable: true},
		{Name: "ready", Type: field.TypeBool, Default: true},
		{Name: "next_check_at", Type: field.TypeTime},
		{Name: "channel_id", Type: field.TypeInt, Unique: true},
	}
	// ProviderQuotaStatusTable holds the schema information for the "provider_quota_status" table.
	ProviderQuotaStatusTable = &schema.Table{
		Name:       "provider_quota_status",
		Columns:    ProviderQuotaStatusColumns,
		PrimaryKey: []*schema.Column{ProviderQuotaStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "provider_quota_status_channels_provider_quota_status",
				Columns:    []*schema.Column{ProviderQuotaStatusColumns[10]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "providerquotastatus_channel_id",
				Unique:  true,
				Columns: []*schema.Column{ProviderQuotaStatusColumns[10]},
			},
			{
				Name:    "providerquotastatus_next_check_at",
				Unique:  false,
				Columns: []*schema.Column{ProviderQuotaStatusColumns[9]},
			},
		},
	}
	// RelaySitesColumns holds the columns for the "relay_sites" table.
	RelaySitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"new_api"}, Default: "new_api"},
		{Name: "base_url", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "auto_checkin_enabled", Type: field.TypeBool, Default: false},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "last_synced_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_sync_error", Type: field.TypeString, Nullable: true},
		{Name: "last_checkin_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_checkin_result", Type: field.TypeString, Nullable: true},
	}
	// RelaySitesTable holds the schema information for the "relay_sites" table.
	RelaySitesTable = &schema.Table{
		Name:       "relay_sites",
		Columns:    RelaySitesColumns,
		PrimaryKey: []*schema.Column{RelaySitesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "relay_sites_by_name",
				Unique:  true,
				Columns: []*schema.Column{RelaySitesColumns[4], RelaySitesColumns[3]},
			},
			{
				Name:    "relaysite_type",
				Unique:  false,
				Columns: []*schema.Column{RelaySitesColumns[5]},
			},
			{
				Name:    "relaysite_status",
				Unique:  false,
				Columns: []*schema.Column{RelaySitesColumns[7]},
			},
		},
	}
	// RelaySiteAPIKeysColumns holds the columns for the "relay_site_api_keys" table.
	RelaySiteAPIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "remote_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "unknown"}, Default: "unknown"},
		{Name: "group_name", Type: field.TypeString, Nullable: true},
		{Name: "quota", Type: field.TypeFloat64, Nullable: true},
		{Name: "used_quota", Type: field.TypeFloat64, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "synced_at", Type: field.TypeTime},
		{Name: "relay_site_id", Type: field.TypeInt},
	}
	// RelaySiteAPIKeysTable holds the schema information for the "relay_site_api_keys" table.
	RelaySiteAPIKeysTable = &schema.Table{
		Name:       "relay_site_api_keys",
		Columns:    RelaySiteAPIKeysColumns,
		PrimaryKey: []*schema.Column{RelaySiteAPIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_site_api_keys_relay_sites_api_keys",
				Columns:    []*schema.Column{RelaySiteAPIKeysColumns[13]},
				RefColumns: []*schema.Column{RelaySitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_site_api_keys_by_site_remote_id",
				Unique:  true,
				Columns: []*schema.Column{RelaySiteAPIKeysColumns[13], RelaySiteAPIKeysColumns[4], RelaySiteAPIKeysColumns[3]},
			},
			{
				Name:    "relaysiteapikey_relay_site_id_status",
				Unique:  false,
				Columns: []*schema.Column{RelaySiteAPIKeysColumns[13], RelaySiteAPIKeysColumns[6]},
			},
			{
				Name:    "relaysiteapikey_relay_site_id_group_name",
				Unique:  false,
				Columns: []*schema.Column{RelaySiteAPIKeysColumns[13], RelaySiteAPIKeysColumns[7]},
			},
		},
	}
	// RelaySiteAnnouncementsColumns holds the columns for the "relay_site_announcements" table.
	RelaySiteAnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "remote_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "extra", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content_hash", Type: field.TypeString},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "fetched_at", Type: field.TypeTime},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "relay_site_id", Type: field.TypeInt},
	}
	// RelaySiteAnnouncementsTable holds the schema information for the "relay_site_announcements" table.
	RelaySiteAnnouncementsTable = &schema.Table{
		Name:       "relay_site_announcements",
		Columns:    RelaySiteAnnouncementsColumns,
		PrimaryKey: []*schema.Column{RelaySiteAnnouncementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_site_announcements_relay_sites_announcements",
				Columns:    []*schema.Column{RelaySiteAnnouncementsColumns[12]},
				RefColumns: []*schema.Column{RelaySitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_site_announcements_by_site_remote",
				Unique:  true,
				Columns: []*schema.Column{RelaySiteAnnouncementsColumns[12], RelaySiteAnnouncementsColumns[3]},
			},
			{
				Name:    "relaysiteannouncement_relay_site_id_read_at",
				Unique:  false,
				Columns: []*schema.Column{RelaySiteAnnouncementsColumns[12], RelaySiteAnnouncementsColumns[10]},
			},
			{
				Name:    "relaysiteannouncement_relay_site_id_published_at",
				Unique:  false,
				Columns: []*schema.Column{RelaySiteAnnouncementsColumns[12], RelaySiteAnnouncementsColumns[8]},
			},
		},
	}
	// RelaySiteBalanceSnapshotsColumns holds the columns for the "relay_site_balance_snapshots" table.
	RelaySiteBalanceSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "balance", Type: field.TypeFloat64},
		{Name: "unit", Type: field.TypeString, Default: "USD"},
		{Name: "pulled_at", Type: field.TypeTime},
		{Name: "relay_site_id", Type: field.TypeInt},
	}
	// RelaySiteBalanceSnapshotsTable holds the schema information for the "relay_site_balance_snapshots" table.
	RelaySiteBalanceSnapshotsTable = &schema.Table{
		Name:       "relay_site_balance_snapshots",
		Columns:    RelaySiteBalanceSnapshotsColumns,
		PrimaryKey: []*schema.Column{RelaySiteBalanceSnapshotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_site_balance_snapshots_relay_sites_balance_snapshots",
				Columns:    []*schema.Column{RelaySiteBalanceSnapshotsColumns[6]},
				RefColumns: []*schema.Column{RelaySitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_site_balance_snapshots_by_site_pulled_at",
				Unique:  false,
				Columns: []*schema.Column{RelaySiteBalanceSnapshotsColumns[6], RelaySiteBalanceSnapshotsColumns[5]},
			},
		},
	}
	// RelaySiteCheckinLogsColumns holds the columns for the "relay_site_checkin_logs" table.
	RelaySiteCheckinLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "executed_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"success", "failed"}},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "relay_site_id", Type: field.TypeInt},
	}
	// RelaySiteCheckinLogsTable holds the schema information for the "relay_site_checkin_logs" table.
	RelaySiteCheckinLogsTable = &schema.Table{
		Name:       "relay_site_checkin_logs",
		Columns:    RelaySiteCheckinLogsColumns,
		PrimaryKey: []*schema.Column{RelaySiteCheckinLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_site_checkin_logs_relay_sites_checkin_logs",
				Columns:    []*schema.Column{RelaySiteCheckinLogsColumns[7]},
				RefColumns: []*schema.Column{RelaySitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_site_checkin_logs_by_site_executed_at",
				Unique:  false,
				Columns: []*schema.Column{RelaySiteCheckinLogsColumns[7], RelaySiteCheckinLogsColumns[3]},
			},
			{
				Name:    "relaysitecheckinlog_relay_site_id_status",
				Unique:  false,
				Columns: []*schema.Column{RelaySiteCheckinLogsColumns[7], RelaySiteCheckinLogsColumns[4]},
			},
		},
	}
	// RelaySiteCredentialsColumns holds the columns for the "relay_site_credentials" table.
	RelaySiteCredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "auth_type", Type: field.TypeEnum, Enums: []string{"token", "password"}},
		{Name: "credential", Type: field.TypeJSON},
		{Name: "relay_site_id", Type: field.TypeInt, Unique: true},
	}
	// RelaySiteCredentialsTable holds the schema information for the "relay_site_credentials" table.
	RelaySiteCredentialsTable = &schema.Table{
		Name:       "relay_site_credentials",
		Columns:    RelaySiteCredentialsColumns,
		PrimaryKey: []*schema.Column{RelaySiteCredentialsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_site_credentials_relay_sites_credential",
				Columns:    []*schema.Column{RelaySiteCredentialsColumns[5]},
				RefColumns: []*schema.Column{RelaySitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relaysitecredential_relay_site_id",
				Unique:  true,
				Columns: []*schema.Column{RelaySiteCredentialsColumns[5]},
			},
		},
	}
	// RelaySiteGroupsColumns holds the columns for the "relay_site_groups" table.
	RelaySiteGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "ratio", Type: field.TypeFloat64, Nullable: true},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "synced_at", Type: field.TypeTime},
		{Name: "relay_site_id", Type: field.TypeInt},
	}
	// RelaySiteGroupsTable holds the schema information for the "relay_site_groups" table.
	RelaySiteGroupsTable = &schema.Table{
		Name:       "relay_site_groups",
		Columns:    RelaySiteGroupsColumns,
		PrimaryKey: []*schema.Column{RelaySiteGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_site_groups_relay_sites_groups",
				Columns:    []*schema.Column{RelaySiteGroupsColumns[8]},
				RefColumns: []*schema.Column{RelaySitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_site_groups_by_site_name",
				Unique:  true,
				Columns: []*schema.Column{RelaySiteGroupsColumns[8], RelaySiteGroupsColumns[4], RelaySiteGroupsColumns[3]},
			},
		},
	}
	// RelaySiteModelPricesColumns holds the columns for the "relay_site_model_prices" table.
	RelaySiteModelPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "model_id", Type: field.TypeString},
		{Name: "price", Type: field.TypeJSON, Nullable: true},
		{Name: "synced_at", Type: field.TypeTime},
		{Name: "relay_site_id", Type: field.TypeInt},
	}
	// RelaySiteModelPricesTable holds the schema information for the "relay_site_model_prices" table.
	RelaySiteModelPricesTable = &schema.Table{
		Name:       "relay_site_model_prices",
		Columns:    RelaySiteModelPricesColumns,
		PrimaryKey: []*schema.Column{RelaySiteModelPricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_site_model_prices_relay_sites_model_prices",
				Columns:    []*schema.Column{RelaySiteModelPricesColumns[7]},
				RefColumns: []*schema.Column{RelaySitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_site_model_prices_by_site_model",
				Unique:  true,
				Columns: []*schema.Column{RelaySiteModelPricesColumns[7], RelaySiteModelPricesColumns[4], RelaySiteModelPricesColumns[3]},
			},
		},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "model_id", Type: field.TypeString},
		{Name: "reasoning_effort", Type: field.TypeString, Nullable: true},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_headers", Type: field.TypeJSON, Nullable: true},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "client_ip", Type: field.TypeString, Default: ""},
		{Name: "metrics_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_first_token_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_reasoning_duration_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "content_saved", Type: field.TypeBool, Default: false},
		{Name: "content_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "content_storage_key", Type: field.TypeString, Nullable: true},
		{Name: "content_saved_at", Type: field.TypeTime, Nullable: true},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "trace_id", Type: field.TypeInt, Nullable: true},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_api_keys_requests",
				Columns:    []*schema.Column{RequestsColumns[22]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_channels_requests",
				Columns:    []*schema.Column{RequestsColumns[23]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_data_storages_requests",
				Columns:    []*schema.Column{RequestsColumns[24]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_projects_requests",
				Columns:    []*schema.Column{RequestsColumns[25]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "requests_traces_requests",
				Columns:    []*schema.Column{RequestsColumns[26]},
				RefColumns: []*schema.Column{TracesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requests_by_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[22], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_project_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[25], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[23], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_trace_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[26], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[1]},
			},
		},
	}
	// RequestExecutionsColumns holds the columns for the "request_executions" table.
	RequestExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "external_id", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "reasoning_effort", Type: field.TypeString, Nullable: true},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "response_status_code", Type: field.TypeInt, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "metrics_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_first_token_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_reasoning_duration_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "request_headers", Type: field.TypeJSON, Nullable: true},
		{Name: "request_url", Type: field.TypeString, Nullable: true},
		{Name: "pass_through_applied", Type: field.TypeBool, Default: false},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "request_id", Type: field.TypeInt},
	}
	// RequestExecutionsTable holds the schema information for the "request_executions" table.
	RequestExecutionsTable = &schema.Table{
		Name:       "request_executions",
		Columns:    RequestExecutionsColumns,
		PrimaryKey: []*schema.Column{RequestExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_executions_channels_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[21]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_data_storages_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[22]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_requests_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[23]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_executions_by_request_id_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[23], RequestExecutionsColumns[13], RequestExecutionsColumns[1]},
			},
			{
				Name:    "request_executions_by_request_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[23], RequestExecutionsColumns[1]},
			},
			{
				Name:    "request_executions_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[21], RequestExecutionsColumns[1]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"system", "project"}, Default: "system"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Nullable: true, Default: 0},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_projects_roles",
				Columns:    []*schema.Column{RolesColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "roles_by_project_id_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[7], RolesColumns[4]},
			},
			{
				Name:    "roles_by_level",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[5]},
			},
		},
	}
	// SystemsColumns holds the columns for the "systems" table.
	SystemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"mysql": "mediumtext"}},
	}
	// SystemsTable holds the schema information for the "systems" table.
	SystemsTable = &schema.Table{
		Name:       "systems",
		Columns:    SystemsColumns,
		PrimaryKey: []*schema.Column{SystemsColumns[0]},
	}
	// ThreadsColumns holds the columns for the "threads" table.
	ThreadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "thread_id", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived", "retained"}, Default: "active"},
		{Name: "project_id", Type: field.TypeInt},
	}
	// ThreadsTable holds the schema information for the "threads" table.
	ThreadsTable = &schema.Table{
		Name:       "threads",
		Columns:    ThreadsColumns,
		PrimaryKey: []*schema.Column{ThreadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "threads_projects_threads",
				Columns:    []*schema.Column{ThreadsColumns[5]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "threads_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{ThreadsColumns[5]},
			},
			{
				Name:    "threads_by_thread_id",
				Unique:  true,
				Columns: []*schema.Column{ThreadsColumns[3]},
			},
			{
				Name:    "threads_by_project_id_status",
				Unique:  false,
				Columns: []*schema.Column{ThreadsColumns[5], ThreadsColumns[4]},
			},
		},
	}
	// TracesColumns holds the columns for the "traces" table.
	TracesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "trace_id", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived", "retained"}, Default: "active"},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "thread_id", Type: field.TypeInt, Nullable: true},
	}
	// TracesTable holds the schema information for the "traces" table.
	TracesTable = &schema.Table{
		Name:       "traces",
		Columns:    TracesColumns,
		PrimaryKey: []*schema.Column{TracesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "traces_projects_traces",
				Columns:    []*schema.Column{TracesColumns[5]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "traces_threads_traces",
				Columns:    []*schema.Column{TracesColumns[6]},
				RefColumns: []*schema.Column{ThreadsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "traces_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[5]},
			},
			{
				Name:    "traces_by_trace_id",
				Unique:  true,
				Columns: []*schema.Column{TracesColumns[3]},
			},
			{
				Name:    "traces_by_thread_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[6]},
			},
			{
				Name:    "traces_by_project_id_status",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[5], TracesColumns[4]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "model_id", Type: field.TypeString},
		{Name: "prompt_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "completion_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "prompt_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_cached_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens_5m", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens_1h", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_reasoning_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_accepted_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_rejected_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "total_cost", Type: field.TypeFloat64, Nullable: true},
		{Name: "cost_items", Type: field.TypeJSON, Nullable: true},
		{Name: "cost_price_reference_id", Type: field.TypeString, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "request_id", Type: field.TypeInt},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_channels_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[22]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_projects_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[23]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_requests_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[24]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usage_logs_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[24]},
			},
			{
				Name:    "usage_logs_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_model_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[4], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_project_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[23], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[22], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[3], UsageLogsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "email", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"activated", "deactivated"}, Default: "activated"},
		{Name: "prefer_language", Type: field.TypeString, Default: "en"},
		{Name: "password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "mediumtext"}},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4], UsersColumns[3]},
			},
		},
	}
	// UserProjectsColumns holds the columns for the "user_projects" table.
	UserProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "project_id", Type: field.TypeInt},
	}
	// UserProjectsTable holds the schema information for the "user_projects" table.
	UserProjectsTable = &schema.Table{
		Name:       "user_projects",
		Columns:    UserProjectsColumns,
		PrimaryKey: []*schema.Column{UserProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_projects_users_user",
				Columns:    []*schema.Column{UserProjectsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_projects_projects_project",
				Columns:    []*schema.Column{UserProjectsColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_projects_by_user_id_project_id",
				Unique:  true,
				Columns: []*schema.Column{UserProjectsColumns[5], UserProjectsColumns[6]},
			},
			{
				Name:    "user_projects_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{UserProjectsColumns[6]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_users_user",
				Columns:    []*schema.Column{UserRolesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_roles_roles_role",
				Columns:    []*schema.Column{UserRolesColumns[4]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_roles_by_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[3], UserRolesColumns[4]},
			},
			{
				Name:    "user_roles_by_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		APIKeyProfileTemplatesTable,
		ChannelsTable,
		ChannelModelPricesTable,
		ChannelModelPriceVersionsTable,
		ChannelOverrideTemplatesTable,
		ChannelProbesTable,
		DataStoragesTable,
		InvitationsTable,
		ModelsTable,
		OidcIdentitiesTable,
		ProjectsTable,
		PromptsTable,
		PromptProtectionRulesTable,
		ProviderQuotaStatusTable,
		RelaySitesTable,
		RelaySiteAPIKeysTable,
		RelaySiteAnnouncementsTable,
		RelaySiteBalanceSnapshotsTable,
		RelaySiteCheckinLogsTable,
		RelaySiteCredentialsTable,
		RelaySiteGroupsTable,
		RelaySiteModelPricesTable,
		RequestsTable,
		RequestExecutionsTable,
		RolesTable,
		SystemsTable,
		ThreadsTable,
		TracesTable,
		UsageLogsTable,
		UsersTable,
		UserProjectsTable,
		UserRolesTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = ProjectsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	APIKeyProfileTemplatesTable.ForeignKeys[0].RefTable = ProjectsTable
	ChannelModelPricesTable.ForeignKeys[0].RefTable = ChannelsTable
	ChannelModelPriceVersionsTable.ForeignKeys[0].RefTable = ChannelModelPricesTable
	ChannelOverrideTemplatesTable.ForeignKeys[0].RefTable = UsersTable
	ChannelProbesTable.ForeignKeys[0].RefTable = ChannelsTable
	InvitationsTable.ForeignKeys[0].RefTable = ProjectsTable
	OidcIdentitiesTable.ForeignKeys[0].RefTable = UsersTable
	PromptsTable.ForeignKeys[0].RefTable = ProjectsTable
	ProviderQuotaStatusTable.ForeignKeys[0].RefTable = ChannelsTable
	RelaySiteAPIKeysTable.ForeignKeys[0].RefTable = RelaySitesTable
	RelaySiteAnnouncementsTable.ForeignKeys[0].RefTable = RelaySitesTable
	RelaySiteBalanceSnapshotsTable.ForeignKeys[0].RefTable = RelaySitesTable
	RelaySiteCheckinLogsTable.ForeignKeys[0].RefTable = RelaySitesTable
	RelaySiteCredentialsTable.ForeignKeys[0].RefTable = RelaySitesTable
	RelaySiteGroupsTable.ForeignKeys[0].RefTable = RelaySitesTable
	RelaySiteModelPricesTable.ForeignKeys[0].RefTable = RelaySitesTable
	RequestsTable.ForeignKeys[0].RefTable = APIKeysTable
	RequestsTable.ForeignKeys[1].RefTable = ChannelsTable
	RequestsTable.ForeignKeys[2].RefTable = DataStoragesTable
	RequestsTable.ForeignKeys[3].RefTable = ProjectsTable
	RequestsTable.ForeignKeys[4].RefTable = TracesTable
	RequestExecutionsTable.ForeignKeys[0].RefTable = ChannelsTable
	RequestExecutionsTable.ForeignKeys[1].RefTable = DataStoragesTable
	RequestExecutionsTable.ForeignKeys[2].RefTable = RequestsTable
	RolesTable.ForeignKeys[0].RefTable = ProjectsTable
	ThreadsTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[1].RefTable = ThreadsTable
	UsageLogsTable.ForeignKeys[0].RefTable = ChannelsTable
	UsageLogsTable.ForeignKeys[1].RefTable = ProjectsTable
	UsageLogsTable.ForeignKeys[2].RefTable = RequestsTable
	UserProjectsTable.ForeignKeys[0].RefTable = UsersTable
	UserProjectsTable.ForeignKeys[1].RefTable = ProjectsTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
}
