// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"
	"sync/atomic"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/schema"
	"github.com/99designs/gqlgen/graphql"
	"github.com/hashicorp/go-multierror"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelmodelprice"
	"github.com/looplj/axonhub/internal/ent/channelmodelpriceversion"
	"github.com/looplj/axonhub/internal/ent/channeloverridetemplate"
	"github.com/looplj/axonhub/internal/ent/channelprobe"
	"github.com/looplj/axonhub/internal/ent/datastorage"
	"github.com/looplj/axonhub/internal/ent/model"
	"github.com/looplj/axonhub/internal/ent/oidcidentity"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/prompt"
	"github.com/looplj/axonhub/internal/ent/promptprotectionrule"
	"github.com/looplj/axonhub/internal/ent/providerquotastatus"
	"github.com/looplj/axonhub/internal/ent/relaysite"
	"github.com/looplj/axonhub/internal/ent/relaysiteannouncement"
	"github.com/looplj/axonhub/internal/ent/relaysiteapikey"
	"github.com/looplj/axonhub/internal/ent/relaysitebalancesnapshot"
	"github.com/looplj/axonhub/internal/ent/relaysitecheckinlog"
	"github.com/looplj/axonhub/internal/ent/relaysitegroup"
	"github.com/looplj/axonhub/internal/ent/relaysitemodelprice"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/ent/role"
	"github.com/looplj/axonhub/internal/ent/system"
	"github.com/looplj/axonhub/internal/ent/thread"
	"github.com/looplj/axonhub/internal/ent/trace"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/ent/userproject"
	"github.com/looplj/axonhub/internal/ent/userrole"
	"golang.org/x/sync/semaphore"
)

// Noder wraps the basic Node method.
type Noder interface {
	Node(context.Context) (*Node, error)
	IsNode()
}

var apikeyImplementors = []string{"APIKey", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*APIKey) IsNode() {}

var apikeyprofiletemplateImplementors = []string{"APIKeyProfileTemplate", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*APIKeyProfileTemplate) IsNode() {}

var channelImplementors = []string{"Channel", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Channel) IsNode() {}

var channelmodelpriceImplementors = []string{"ChannelModelPrice", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ChannelModelPrice) IsNode() {}

var channelmodelpriceversionImplementors = []string{"ChannelModelPriceVersion", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ChannelModelPriceVersion) IsNode() {}

var channeloverridetemplateImplementors = []string{"ChannelOverrideTemplate", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ChannelOverrideTemplate) IsNode() {}

var channelprobeImplementors = []string{"ChannelProbe", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ChannelProbe) IsNode() {}

var datastorageImplementors = []string{"DataStorage", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*DataStorage) IsNode() {}

var modelImplementors = []string{"Model", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Model) IsNode() {}

var oidcidentityImplementors = []string{"OIDCIdentity", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*OIDCIdentity) IsNode() {}

var projectImplementors = []string{"Project", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Project) IsNode() {}

var promptImplementors = []string{"Prompt", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Prompt) IsNode() {}

var promptprotectionruleImplementors = []string{"PromptProtectionRule", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*PromptProtectionRule) IsNode() {}

var providerquotastatusImplementors = []string{"ProviderQuotaStatus", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProviderQuotaStatus) IsNode() {}

var relaysiteImplementors = []string{"RelaySite", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RelaySite) IsNode() {}

var relaysiteapikeyImplementors = []string{"RelaySiteAPIKey", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RelaySiteAPIKey) IsNode() {}

var relaysiteannouncementImplementors = []string{"RelaySiteAnnouncement", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RelaySiteAnnouncement) IsNode() {}

var relaysitebalancesnapshotImplementors = []string{"RelaySiteBalanceSnapshot", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RelaySiteBalanceSnapshot) IsNode() {}

var relaysitecheckinlogImplementors = []string{"RelaySiteCheckinLog", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RelaySiteCheckinLog) IsNode() {}

var relaysitegroupImplementors = []string{"RelaySiteGroup", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RelaySiteGroup) IsNode() {}

var relaysitemodelpriceImplementors = []string{"RelaySiteModelPrice", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RelaySiteModelPrice) IsNode() {}

var requestImplementors = []string{"Request", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Request) IsNode() {}

var requestexecutionImplementors = []string{"RequestExecution", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*RequestExecution) IsNode() {}

var roleImplementors = []string{"Role", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Role) IsNode() {}

var systemImplementors = []string{"System", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*System) IsNode() {}

var threadImplementors = []string{"Thread", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Thread) IsNode() {}

var traceImplementors = []string{"Trace", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Trace) IsNode() {}

var usagelogImplementors = []string{"UsageLog", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*UsageLog) IsNode() {}

var userImplementors = []string{"User", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*User) IsNode() {}

var userprojectImplementors = []string{"UserProject", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*UserProject) IsNode() {}

var userroleImplementors = []string{"UserRole", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*UserRole) IsNode() {}

var errNodeInvalidID = &NotFoundError{"node"}

// NodeOption allows configuring the Noder execution using functional options.
type NodeOption func(*nodeOptions)

// WithNodeType sets the node Type resolver function (i.e. the table to query).
// If was not provided, the table will be derived from the universal-id
// configuration as described in: https://entgo.io/docs/migrate/#universal-ids.
func WithNodeType(f func(context.Context, int) (string, error)) NodeOption {
	return func(o *nodeOptions) {
		o.nodeType = f
	}
}

// WithFixedNodeType sets the Type of the node to a fixed value.
func WithFixedNodeType(t string) NodeOption {
	return WithNodeType(func(context.Context, int) (string, error) {
		return t, nil
	})
}

type nodeOptions struct {
	nodeType func(context.Context, int) (string, error)
}

func (c *Client) newNodeOpts(opts []NodeOption) *nodeOptions {
	nopts := &nodeOptions{}
	for _, opt := range opts {
		opt(nopts)
	}
	if nopts.nodeType == nil {
		nopts.nodeType = func(ctx context.Context, id int) (string, error) {
			return c.tables.nodeType(ctx, c.driver, id)
		}
	}
	return nopts
}

// Noder returns a Node by its id. If the NodeType was not provided, it will
// be derived from the id value according to the universal-id configuration.
//
//	c.Noder(ctx, id)
//	c.Noder(ctx, id, ent.WithNodeType(typeResolver))
func (c *Client) Noder(ctx context.Context, id int, opts ...NodeOption) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	table, err := c.newNodeOpts(opts).nodeType(ctx, id)
	if err != nil {
		return nil, err
	}
	return c.noder(ctx, table, id)
}

func (c *Client) noder(ctx context.Context, table string, id int) (Noder, error) {
	switch table {
	case apikey.Table:
		query := c.APIKey.Query().
			Where(apikey.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, apikeyImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case apikeyprofiletemplate.Table:
		query := c.APIKeyProfileTemplate.Query().
			Where(apikeyprofiletemplate.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, apikeyprofiletemplateImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case channel.Table:
		query := c.Channel.Query().
			Where(channel.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, channelImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case channelmodelprice.Table:
		query := c.ChannelModelPrice.Query().
			Where(channelmodelprice.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, channelmodelpriceImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case channelmodelpriceversion.Table:
		query := c.ChannelModelPriceVersion.Query().
			Where(channelmodelpriceversion.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, channelmodelpriceversionImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case channeloverridetemplate.Table:
		query := c.ChannelOverrideTemplate.Query().
			Where(channeloverridetemplate.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, channeloverridetemplateImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case channelprobe.Table:
		query := c.ChannelProbe.Query().
			Where(channelprobe.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, channelprobeImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case datastorage.Table:
		query := c.DataStorage.Query().
			Where(datastorage.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, datastorageImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case model.Table:
		query := c.Model.Query().
			Where(model.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, modelImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case oidcidentity.Table:
		query := c.OIDCIdentity.Query().
			Where(oidcidentity.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, oidcidentityImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case project.Table:
		query := c.Project.Query().
			Where(project.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, projectImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case prompt.Table:
		query := c.Prompt.Query().
			Where(prompt.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, promptImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case promptprotectionrule.Table:
		query := c.PromptProtectionRule.Query().
			Where(promptprotectionrule.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, promptprotectionruleImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case providerquotastatus.Table:
		query := c.ProviderQuotaStatus.Query().
			Where(providerquotastatus.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, providerquotastatusImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case relaysite.Table:
		query := c.RelaySite.Query().
			Where(relaysite.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, relaysiteImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case relaysiteapikey.Table:
		query := c.RelaySiteAPIKey.Query().
			Where(relaysiteapikey.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, relaysiteapikeyImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case relaysiteannouncement.Table:
		query := c.RelaySiteAnnouncement.Query().
			Where(relaysiteannouncement.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, relaysiteannouncementImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case relaysitebalancesnapshot.Table:
		query := c.RelaySiteBalanceSnapshot.Query().
			Where(relaysitebalancesnapshot.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, relaysitebalancesnapshotImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case relaysitecheckinlog.Table:
		query := c.RelaySiteCheckinLog.Query().
			Where(relaysitecheckinlog.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, relaysitecheckinlogImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case relaysitegroup.Table:
		query := c.RelaySiteGroup.Query().
			Where(relaysitegroup.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, relaysitegroupImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case relaysitemodelprice.Table:
		query := c.RelaySiteModelPrice.Query().
			Where(relaysitemodelprice.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, relaysitemodelpriceImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case request.Table:
		query := c.Request.Query().
			Where(request.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, requestImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case requestexecution.Table:
		query := c.RequestExecution.Query().
			Where(requestexecution.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, requestexecutionImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case role.Table:
		query := c.Role.Query().
			Where(role.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, roleImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case system.Table:
		query := c.System.Query().
			Where(system.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, systemImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case thread.Table:
		query := c.Thread.Query().
			Where(thread.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, threadImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case trace.Table:
		query := c.Trace.Query().
			Where(trace.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, traceImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case usagelog.Table:
		query := c.UsageLog.Query().
			Where(usagelog.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, usagelogImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case user.Table:
		query := c.User.Query().
			Where(user.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, userImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case userproject.Table:
		query := c.UserProject.Query().
			Where(userproject.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, userprojectImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case userrole.Table:
		query := c.UserRole.Query().
			Where(userrole.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, userroleImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	default:
		return nil, fmt.Errorf("cannot resolve noder from table %q: %w", table, errNodeInvalidID)
	}
}

func (c *Client) Noders(ctx context.Context, ids []int, opts ...NodeOption) ([]Noder, error) {
	switch len(ids) {
	case 1:
		noder, err := c.Noder(ctx, ids[0], opts...)
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}

	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	tables := make(map[string][]int)
	id2idx := make(map[int][]int, len(ids))
	nopts := c.newNodeOpts(opts)
	for i, id := range ids {
		table, err := nopts.nodeType(ctx, id)
		if err != nil {
			errors[i] = err
			continue
		}
		tables[table] = append(tables[table], id)
		id2idx[id] = append(id2idx[id], i)
	}

	for table, ids := range tables {
		nodes, err := c.noders(ctx, table, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) noders(ctx context.Context, table string, ids []int) ([]Noder, error) {
	noders := make([]Noder, len(ids))
	idmap := make(map[int][]*Noder, len(ids))
	for i, id := range ids {
		idmap[id] = append(idmap[id], &noders[i])
	}
	switch table {
	case apikey.Table:
		query := c.APIKey.Query().
			Where(apikey.IDIn(ids...))
		query, err := query.CollectFields(ctx, apikeyImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case apikeyprofiletemplate.Table:
		query := c.APIKeyProfileTemplate.Query().
			Where(apikeyprofiletemplate.IDIn(ids...))
		query, err := query.CollectFields(ctx, apikeyprofiletemplateImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case channel.Table:
		query := c.Channel.Query().
			Where(channel.IDIn(ids...))
		query, err := query.CollectFields(ctx, channelImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case channelmodelprice.Table:
		query := c.ChannelModelPrice.Query().
			Where(channelmodelprice.IDIn(ids...))
		query, err := query.CollectFields(ctx, channelmodelpriceImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case channelmodelpriceversion.Table:
		query := c.ChannelModelPriceVersion.Query().
			Where(channelmodelpriceversion.IDIn(ids...))
		query, err := query.CollectFields(ctx, channelmodelpriceversionImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case channeloverridetemplate.Table:
		query := c.ChannelOverrideTemplate.Query().
			Where(channeloverridetemplate.IDIn(ids...))
		query, err := query.CollectFields(ctx, channeloverridetemplateImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case channelprobe.Table:
		query := c.ChannelProbe.Query().
			Where(channelprobe.IDIn(ids...))
		query, err := query.CollectFields(ctx, channelprobeImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case datastorage.Table:
		query := c.DataStorage.Query().
			Where(datastorage.IDIn(ids...))
		query, err := query.CollectFields(ctx, datastorageImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case model.Table:
		query := c.Model.Query().
			Where(model.IDIn(ids...))
		query, err := query.CollectFields(ctx, modelImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case oidcidentity.Table:
		query := c.OIDCIdentity.Query().
			Where(oidcidentity.IDIn(ids...))
		query, err := query.CollectFields(ctx, oidcidentityImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case project.Table:
		query := c.Project.Query().
			Where(project.IDIn(ids...))
		query, err := query.CollectFields(ctx, projectImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case prompt.Table:
		query := c.Prompt.Query().
			Where(prompt.IDIn(ids...))
		query, err := query.CollectFields(ctx, promptImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case promptprotectionrule.Table:
		query := c.PromptProtectionRule.Query().
			Where(promptprotectionrule.IDIn(ids...))
		query, err := query.CollectFields(ctx, promptprotectionruleImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case providerquotastatus.Table:
		query := c.ProviderQuotaStatus.Query().
			Where(providerquotastatus.IDIn(ids...))
		query, err := query.CollectFields(ctx, providerquotastatusImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case relaysite.Table:
		query := c.RelaySite.Query().
			Where(relaysite.IDIn(ids...))
		query, err := query.CollectFields(ctx, relaysiteImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case relaysiteapikey.Table:
		query := c.RelaySiteAPIKey.Query().
			Where(relaysiteapikey.IDIn(ids...))
		query, err := query.CollectFields(ctx, relaysiteapikeyImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case relaysiteannouncement.Table:
		query := c.RelaySiteAnnouncement.Query().
			Where(relaysiteannouncement.IDIn(ids...))
		query, err := query.CollectFields(ctx, relaysiteannouncementImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case relaysitebalancesnapshot.Table:
		query := c.RelaySiteBalanceSnapshot.Query().
			Where(relaysitebalancesnapshot.IDIn(ids...))
		query, err := query.CollectFields(ctx, relaysitebalancesnapshotImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case relaysitecheckinlog.Table:
		query := c.RelaySiteCheckinLog.Query().
			Where(relaysitecheckinlog.IDIn(ids...))
		query, err := query.CollectFields(ctx, relaysitecheckinlogImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case relaysitegroup.Table:
		query := c.RelaySiteGroup.Query().
			Where(relaysitegroup.IDIn(ids...))
		query, err := query.CollectFields(ctx, relaysitegroupImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case relaysitemodelprice.Table:
		query := c.RelaySiteModelPrice.Query().
			Where(relaysitemodelprice.IDIn(ids...))
		query, err := query.CollectFields(ctx, relaysitemodelpriceImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case request.Table:
		query := c.Request.Query().
			Where(request.IDIn(ids...))
		query, err := query.CollectFields(ctx, requestImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case requestexecution.Table:
		query := c.RequestExecution.Query().
			Where(requestexecution.IDIn(ids...))
		query, err := query.CollectFields(ctx, requestexecutionImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case role.Table:
		query := c.Role.Query().
			Where(role.IDIn(ids...))
		query, err := query.CollectFields(ctx, roleImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case system.Table:
		query := c.System.Query().
			Where(system.IDIn(ids...))
		query, err := query.CollectFields(ctx, systemImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case thread.Table:
		query := c.Thread.Query().
			Where(thread.IDIn(ids...))
		query, err := query.CollectFields(ctx, threadImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case trace.Table:
		query := c.Trace.Query().
			Where(trace.IDIn(ids...))
		query, err := query.CollectFields(ctx, traceImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case usagelog.Table:
		query := c.UsageLog.Query().
			Where(usagelog.IDIn(ids...))
		query, err := query.CollectFields(ctx, usagelogImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case user.Table:
		query := c.User.Query().
			Where(user.IDIn(ids...))
		query, err := query.CollectFields(ctx, userImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case userproject.Table:
		query := c.UserProject.Query().
			Where(userproject.IDIn(ids...))
		query, err := query.CollectFields(ctx, userprojectImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case userrole.Table:
		query := c.UserRole.Query().
			Where(userrole.IDIn(ids...))
		query, err := query.CollectFields(ctx, userroleImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from table %q: %w", table, errNodeInvalidID)
	}
	return noders, nil
}

type tables struct {
	once  sync.Once
	sem   *semaphore.Weighted
	value atomic.Value
}

func (t *tables) nodeType(ctx context.Context, drv dialect.Driver, id int) (string, error) {
	tables, err := t.Load(ctx, drv)
	if err != nil {
		return "", err
	}
	idx := int(id / (1<<32 - 1))
	if idx < 0 || idx >= len(tables) {
		return "", fmt.Errorf("cannot resolve table from id %v: %w", id, errNodeInvalidID)
	}
	return tables[idx], nil
}

func (t *tables) Load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	t.once.Do(func() { t.sem = semaphore.NewWeighted(1) })
	if err := t.sem.Acquire(ctx, 1); err != nil {
		return nil, err
	}
	defer t.sem.Release(1)
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	tables, err := t.load(ctx, drv)
	if err == nil {
		t.value.Store(tables)
	}
	return tables, err
}

func (*tables) load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	rows := &sql.Rows{}
	query, args := sql.Dialect(drv.Dialect()).
		Select("type").
		From(sql.Table(schema.TypeTable)).
		OrderBy(sql.Asc("id")).
		Query()
	if err := drv.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	return tables, sql.ScanSlice(rows, &tables)
}
