// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/relaysite"
	"github.com/looplj/axonhub/internal/ent/relaysitemodelprice"
)

// RelaySiteModelPriceQuery is the builder for querying RelaySiteModelPrice entities.
type RelaySiteModelPriceQuery struct {
	config
	ctx           *QueryContext
	order         []relaysitemodelprice.OrderOption
	inters        []Interceptor
	predicates    []predicate.RelaySiteModelPrice
	withRelaySite *RelaySiteQuery
	loadTotal     []func(context.Context, []*RelaySiteModelPrice) error
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RelaySiteModelPriceQuery builder.
func (_q *RelaySiteModelPriceQuery) Where(ps ...predicate.RelaySiteModelPrice) *RelaySiteModelPriceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RelaySiteModelPriceQuery) Limit(limit int) *RelaySiteModelPriceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RelaySiteModelPriceQuery) Offset(offset int) *RelaySiteModelPriceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RelaySiteModelPriceQuery) Unique(unique bool) *RelaySiteModelPriceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RelaySiteModelPriceQuery) Order(o ...relaysitemodelprice.OrderOption) *RelaySiteModelPriceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRelaySite chains the current query on the "relay_site" edge.
func (_q *RelaySiteModelPriceQuery) QueryRelaySite() *RelaySiteQuery {
	query := (&RelaySiteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaysitemodelprice.Table, relaysitemodelprice.FieldID, selector),
			sqlgraph.To(relaysite.Table, relaysite.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relaysitemodelprice.RelaySiteTable, relaysitemodelprice.RelaySiteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RelaySiteModelPrice entity from the query.
// Returns a *NotFoundError when no RelaySiteModelPrice was found.
func (_q *RelaySiteModelPriceQuery) First(ctx context.Context) (*RelaySiteModelPrice, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{relaysitemodelprice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) FirstX(ctx context.Context) *RelaySiteModelPrice {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RelaySiteModelPrice ID from the query.
// Returns a *NotFoundError when no RelaySiteModelPrice ID was found.
func (_q *RelaySiteModelPriceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{relaysitemodelprice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RelaySiteModelPrice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RelaySiteModelPrice entity is found.
// Returns a *NotFoundError when no RelaySiteModelPrice entities are found.
func (_q *RelaySiteModelPriceQuery) Only(ctx context.Context) (*RelaySiteModelPrice, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{relaysitemodelprice.Label}
	default:
		return nil, &NotSingularError{relaysitemodelprice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) OnlyX(ctx context.Context) *RelaySiteModelPrice {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RelaySiteModelPrice ID in the query.
// Returns a *NotSingularError when more than one RelaySiteModelPrice ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RelaySiteModelPriceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{relaysitemodelprice.Label}
	default:
		err = &NotSingularError{relaysitemodelprice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RelaySiteModelPrices.
func (_q *RelaySiteModelPriceQuery) All(ctx context.Context) ([]*RelaySiteModelPrice, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RelaySiteModelPrice, *RelaySiteModelPriceQuery]()
	return withInterceptors[[]*RelaySiteModelPrice](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) AllX(ctx context.Context) []*RelaySiteModelPrice {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RelaySiteModelPrice IDs.
func (_q *RelaySiteModelPriceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(relaysitemodelprice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RelaySiteModelPriceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RelaySiteModelPriceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RelaySiteModelPriceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RelaySiteModelPriceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RelaySiteModelPriceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RelaySiteModelPriceQuery) Clone() *RelaySiteModelPriceQuery {
	if _q == nil {
		return nil
	}
	return &RelaySiteModelPriceQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]relaysitemodelprice.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.RelaySiteModelPrice{}, _q.predicates...),
		withRelaySite: _q.withRelaySite.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithRelaySite tells the query-builder to eager-load the nodes that are connected to
// the "relay_site" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelaySiteModelPriceQuery) WithRelaySite(opts ...func(*RelaySiteQuery)) *RelaySiteModelPriceQuery {
	query := (&RelaySiteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRelaySite = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RelaySiteModelPrice.Query().
//		GroupBy(relaysitemodelprice.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RelaySiteModelPriceQuery) GroupBy(field string, fields ...string) *RelaySiteModelPriceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RelaySiteModelPriceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = relaysitemodelprice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.RelaySiteModelPrice.Query().
//		Select(relaysitemodelprice.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *RelaySiteModelPriceQuery) Select(fields ...string) *RelaySiteModelPriceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RelaySiteModelPriceSelect{RelaySiteModelPriceQuery: _q}
	sbuild.label = relaysitemodelprice.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RelaySiteModelPriceSelect configured with the given aggregations.
func (_q *RelaySiteModelPriceQuery) Aggregate(fns ...AggregateFunc) *RelaySiteModelPriceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RelaySiteModelPriceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !relaysitemodelprice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if relaysitemodelprice.Policy == nil {
		return errors.New("ent: uninitialized relaysitemodelprice.Policy (forgotten import ent/runtime?)")
	}
	if err := relaysitemodelprice.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *RelaySiteModelPriceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RelaySiteModelPrice, error) {
	var (
		nodes       = []*RelaySiteModelPrice{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withRelaySite != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RelaySiteModelPrice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RelaySiteModelPrice{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRelaySite; query != nil {
		if err := _q.loadRelaySite(ctx, query, nodes, nil,
			func(n *RelaySiteModelPrice, e *RelaySite) { n.Edges.RelaySite = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RelaySiteModelPriceQuery) loadRelaySite(ctx context.Context, query *RelaySiteQuery, nodes []*RelaySiteModelPrice, init func(*RelaySiteModelPrice), assign func(*RelaySiteModelPrice, *RelaySite)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelaySiteModelPrice)
	for i := range nodes {
		fk := nodes[i].RelaySiteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(relaysite.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "relay_site_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RelaySiteModelPriceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RelaySiteModelPriceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(relaysitemodelprice.Table, relaysitemodelprice.Columns, sqlgraph.NewFieldSpec(relaysitemodelprice.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaysitemodelprice.FieldID)
		for i := range fields {
			if fields[i] != relaysitemodelprice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRelaySite != nil {
			_spec.Node.AddColumnOnce(relaysitemodelprice.FieldRelaySiteID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RelaySiteModelPriceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(relaysitemodelprice.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = relaysitemodelprice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *RelaySiteModelPriceQuery) Modify(modifiers ...func(s *sql.Selector)) *RelaySiteModelPriceSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// RelaySiteModelPriceGroupBy is the group-by builder for RelaySiteModelPrice entities.
type RelaySiteModelPriceGroupBy struct {
	selector
	build *RelaySiteModelPriceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RelaySiteModelPriceGroupBy) Aggregate(fns ...AggregateFunc) *RelaySiteModelPriceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RelaySiteModelPriceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelaySiteModelPriceQuery, *RelaySiteModelPriceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RelaySiteModelPriceGroupBy) sqlScan(ctx context.Context, root *RelaySiteModelPriceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RelaySiteModelPriceSelect is the builder for selecting fields of RelaySiteModelPrice entities.
type RelaySiteModelPriceSelect struct {
	*RelaySiteModelPriceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RelaySiteModelPriceSelect) Aggregate(fns ...AggregateFunc) *RelaySiteModelPriceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RelaySiteModelPriceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelaySiteModelPriceQuery, *RelaySiteModelPriceSelect](ctx, _s.RelaySiteModelPriceQuery, _s, _s.inters, v)
}

func (_s *RelaySiteModelPriceSelect) sqlScan(ctx context.Context, root *RelaySiteModelPriceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *RelaySiteModelPriceSelect) Modify(modifiers ...func(s *sql.Selector)) *RelaySiteModelPriceSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
