// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/relaysite"
	"github.com/looplj/axonhub/internal/ent/relaysitegroup"
	"github.com/looplj/axonhub/internal/objects"
)

// RelaySiteGroupCreate is the builder for creating a RelaySiteGroup entity.
type RelaySiteGroupCreate struct {
	config
	mutation *RelaySiteGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelaySiteGroupCreate) SetCreatedAt(v time.Time) *RelaySiteGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelaySiteGroupCreate) SetNillableCreatedAt(v *time.Time) *RelaySiteGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelaySiteGroupCreate) SetUpdatedAt(v time.Time) *RelaySiteGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelaySiteGroupCreate) SetNillableUpdatedAt(v *time.Time) *RelaySiteGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RelaySiteGroupCreate) SetDeletedAt(v int) *RelaySiteGroupCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RelaySiteGroupCreate) SetNillableDeletedAt(v *int) *RelaySiteGroupCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetRelaySiteID sets the "relay_site_id" field.
func (_c *RelaySiteGroupCreate) SetRelaySiteID(v int) *RelaySiteGroupCreate {
	_c.mutation.SetRelaySiteID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RelaySiteGroupCreate) SetName(v string) *RelaySiteGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRatio sets the "ratio" field.
func (_c *RelaySiteGroupCreate) SetRatio(v float64) *RelaySiteGroupCreate {
	_c.mutation.SetRatio(v)
	return _c
}

// SetNillableRatio sets the "ratio" field if the given value is not nil.
func (_c *RelaySiteGroupCreate) SetNillableRatio(v *float64) *RelaySiteGroupCreate {
	if v != nil {
		_c.SetRatio(*v)
	}
	return _c
}

// SetSettings sets the "settings" field.
func (_c *RelaySiteGroupCreate) SetSettings(v objects.RelaySiteGroupSettings) *RelaySiteGroupCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// SetNillableSettings sets the "settings" field if the given value is not nil.
func (_c *RelaySiteGroupCreate) SetNillableSettings(v *objects.RelaySiteGroupSettings) *RelaySiteGroupCreate {
	if v != nil {
		_c.SetSettings(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *RelaySiteGroupCreate) SetSyncedAt(v time.Time) *RelaySiteGroupCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetRelaySite sets the "relay_site" edge to the RelaySite entity.
func (_c *RelaySiteGroupCreate) SetRelaySite(v *RelaySite) *RelaySiteGroupCreate {
	return _c.SetRelaySiteID(v.ID)
}

// Mutation returns the RelaySiteGroupMutation object of the builder.
func (_c *RelaySiteGroupCreate) Mutation() *RelaySiteGroupMutation {
	return _c.mutation
}

// Save creates the RelaySiteGroup in the database.
func (_c *RelaySiteGroupCreate) Save(ctx context.Context) (*RelaySiteGroup, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelaySiteGroupCreate) SaveX(ctx context.Context) *RelaySiteGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelaySiteGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelaySiteGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelaySiteGroupCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if relaysitegroup.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysitegroup.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := relaysitegroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if relaysitegroup.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysitegroup.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaysitegroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := relaysitegroup.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Settings(); !ok {
		v := relaysitegroup.DefaultSettings
		_c.mutation.SetSettings(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelaySiteGroupCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "RelaySiteGroup.deleted_at"`)}
	}
	if _, ok := _c.mutation.RelaySiteID(); !ok {
		return &ValidationError{Name: "relay_site_id", err: errors.New(`ent: missing required field "RelaySiteGroup.relay_site_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RelaySiteGroup.name"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "RelaySiteGroup.synced_at"`)}
	}
	if len(_c.mutation.RelaySiteIDs()) == 0 {
		return &ValidationError{Name: "relay_site", err: errors.New(`ent: missing required edge "RelaySiteGroup.relay_site"`)}
	}
	return nil
}

func (_c *RelaySiteGroupCreate) sqlSave(ctx context.Context) (*RelaySiteGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelaySiteGroupCreate) createSpec() (*RelaySiteGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &RelaySiteGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relaysitegroup.Table, sqlgraph.NewFieldSpec(relaysitegroup.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relaysitegroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relaysitegroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(relaysitegroup.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(relaysitegroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Ratio(); ok {
		_spec.SetField(relaysitegroup.FieldRatio, field.TypeFloat64, value)
		_node.Ratio = &value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(relaysitegroup.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(relaysitegroup.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if nodes := _c.mutation.RelaySiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaysitegroup.RelaySiteTable,
			Columns: []string{relaysitegroup.RelaySiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaysite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RelaySiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelaySiteGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelaySiteGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelaySiteGroupCreate) OnConflict(opts ...sql.ConflictOption) *RelaySiteGroupUpsertOne {
	_c.conflict = opts
	return &RelaySiteGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelaySiteGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelaySiteGroupCreate) OnConflictColumns(columns ...string) *RelaySiteGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelaySiteGroupUpsertOne{
		create: _c,
	}
}

type (
	// RelaySiteGroupUpsertOne is the builder for "upsert"-ing
	//  one RelaySiteGroup node.
	RelaySiteGroupUpsertOne struct {
		create *RelaySiteGroupCreate
	}

	// RelaySiteGroupUpsert is the "OnConflict" setter.
	RelaySiteGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteGroupUpsert) SetUpdatedAt(v time.Time) *RelaySiteGroupUpsert {
	u.Set(relaysitegroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsert) UpdateUpdatedAt() *RelaySiteGroupUpsert {
	u.SetExcluded(relaysitegroup.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RelaySiteGroupUpsert) SetDeletedAt(v int) *RelaySiteGroupUpsert {
	u.Set(relaysitegroup.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsert) UpdateDeletedAt() *RelaySiteGroupUpsert {
	u.SetExcluded(relaysitegroup.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RelaySiteGroupUpsert) AddDeletedAt(v int) *RelaySiteGroupUpsert {
	u.Add(relaysitegroup.FieldDeletedAt, v)
	return u
}

// SetRatio sets the "ratio" field.
func (u *RelaySiteGroupUpsert) SetRatio(v float64) *RelaySiteGroupUpsert {
	u.Set(relaysitegroup.FieldRatio, v)
	return u
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *RelaySiteGroupUpsert) UpdateRatio() *RelaySiteGroupUpsert {
	u.SetExcluded(relaysitegroup.FieldRatio)
	return u
}

// AddRatio adds v to the "ratio" field.
func (u *RelaySiteGroupUpsert) AddRatio(v float64) *RelaySiteGroupUpsert {
	u.Add(relaysitegroup.FieldRatio, v)
	return u
}

// ClearRatio clears the value of the "ratio" field.
func (u *RelaySiteGroupUpsert) ClearRatio() *RelaySiteGroupUpsert {
	u.SetNull(relaysitegroup.FieldRatio)
	return u
}

// SetSettings sets the "settings" field.
func (u *RelaySiteGroupUpsert) SetSettings(v objects.RelaySiteGroupSettings) *RelaySiteGroupUpsert {
	u.Set(relaysitegroup.FieldSettings, v)
	return u
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *RelaySiteGroupUpsert) UpdateSettings() *RelaySiteGroupUpsert {
	u.SetExcluded(relaysitegroup.FieldSettings)
	return u
}

// ClearSettings clears the value of the "settings" field.
func (u *RelaySiteGroupUpsert) ClearSettings() *RelaySiteGroupUpsert {
	u.SetNull(relaysitegroup.FieldSettings)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *RelaySiteGroupUpsert) SetSyncedAt(v time.Time) *RelaySiteGroupUpsert {
	u.Set(relaysitegroup.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsert) UpdateSyncedAt() *RelaySiteGroupUpsert {
	u.SetExcluded(relaysitegroup.FieldSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RelaySiteGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelaySiteGroupUpsertOne) UpdateNewValues() *RelaySiteGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(relaysitegroup.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.RelaySiteID(); exists {
			s.SetIgnore(relaysitegroup.FieldRelaySiteID)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(relaysitegroup.FieldName)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelaySiteGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RelaySiteGroupUpsertOne) Ignore() *RelaySiteGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelaySiteGroupUpsertOne) DoNothing() *RelaySiteGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelaySiteGroupCreate.OnConflict
// documentation for more info.
func (u *RelaySiteGroupUpsertOne) Update(set func(*RelaySiteGroupUpsert)) *RelaySiteGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelaySiteGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteGroupUpsertOne) SetUpdatedAt(v time.Time) *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertOne) UpdateUpdatedAt() *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RelaySiteGroupUpsertOne) SetDeletedAt(v int) *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RelaySiteGroupUpsertOne) AddDeletedAt(v int) *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertOne) UpdateDeletedAt() *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetRatio sets the "ratio" field.
func (u *RelaySiteGroupUpsertOne) SetRatio(v float64) *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetRatio(v)
	})
}

// AddRatio adds v to the "ratio" field.
func (u *RelaySiteGroupUpsertOne) AddRatio(v float64) *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.AddRatio(v)
	})
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertOne) UpdateRatio() *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateRatio()
	})
}

// ClearRatio clears the value of the "ratio" field.
func (u *RelaySiteGroupUpsertOne) ClearRatio() *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.ClearRatio()
	})
}

// SetSettings sets the "settings" field.
func (u *RelaySiteGroupUpsertOne) SetSettings(v objects.RelaySiteGroupSettings) *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertOne) UpdateSettings() *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateSettings()
	})
}

// ClearSettings clears the value of the "settings" field.
func (u *RelaySiteGroupUpsertOne) ClearSettings() *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.ClearSettings()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *RelaySiteGroupUpsertOne) SetSyncedAt(v time.Time) *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertOne) UpdateSyncedAt() *RelaySiteGroupUpsertOne {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *RelaySiteGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelaySiteGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelaySiteGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RelaySiteGroupUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RelaySiteGroupUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RelaySiteGroupCreateBulk is the builder for creating many RelaySiteGroup entities in bulk.
type RelaySiteGroupCreateBulk struct {
	config
	err      error
	builders []*RelaySiteGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the RelaySiteGroup entities in the database.
func (_c *RelaySiteGroupCreateBulk) Save(ctx context.Context) ([]*RelaySiteGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelaySiteGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelaySiteGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelaySiteGroupCreateBulk) SaveX(ctx context.Context) []*RelaySiteGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelaySiteGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelaySiteGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelaySiteGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelaySiteGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelaySiteGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *RelaySiteGroupUpsertBulk {
	_c.conflict = opts
	return &RelaySiteGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelaySiteGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelaySiteGroupCreateBulk) OnConflictColumns(columns ...string) *RelaySiteGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelaySiteGroupUpsertBulk{
		create: _c,
	}
}

// RelaySiteGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of RelaySiteGroup nodes.
type RelaySiteGroupUpsertBulk struct {
	create *RelaySiteGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RelaySiteGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelaySiteGroupUpsertBulk) UpdateNewValues() *RelaySiteGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(relaysitegroup.FieldCreatedAt)
			}
			if _, exists := b.mutation.RelaySiteID(); exists {
				s.SetIgnore(relaysitegroup.FieldRelaySiteID)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(relaysitegroup.FieldName)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelaySiteGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RelaySiteGroupUpsertBulk) Ignore() *RelaySiteGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelaySiteGroupUpsertBulk) DoNothing() *RelaySiteGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelaySiteGroupCreateBulk.OnConflict
// documentation for more info.
func (u *RelaySiteGroupUpsertBulk) Update(set func(*RelaySiteGroupUpsert)) *RelaySiteGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelaySiteGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteGroupUpsertBulk) SetUpdatedAt(v time.Time) *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertBulk) UpdateUpdatedAt() *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RelaySiteGroupUpsertBulk) SetDeletedAt(v int) *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RelaySiteGroupUpsertBulk) AddDeletedAt(v int) *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertBulk) UpdateDeletedAt() *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetRatio sets the "ratio" field.
func (u *RelaySiteGroupUpsertBulk) SetRatio(v float64) *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetRatio(v)
	})
}

// AddRatio adds v to the "ratio" field.
func (u *RelaySiteGroupUpsertBulk) AddRatio(v float64) *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.AddRatio(v)
	})
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertBulk) UpdateRatio() *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateRatio()
	})
}

// ClearRatio clears the value of the "ratio" field.
func (u *RelaySiteGroupUpsertBulk) ClearRatio() *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.ClearRatio()
	})
}

// SetSettings sets the "settings" field.
func (u *RelaySiteGroupUpsertBulk) SetSettings(v objects.RelaySiteGroupSettings) *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertBulk) UpdateSettings() *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateSettings()
	})
}

// ClearSettings clears the value of the "settings" field.
func (u *RelaySiteGroupUpsertBulk) ClearSettings() *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.ClearSettings()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *RelaySiteGroupUpsertBulk) SetSyncedAt(v time.Time) *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *RelaySiteGroupUpsertBulk) UpdateSyncedAt() *RelaySiteGroupUpsertBulk {
	return u.Update(func(s *RelaySiteGroupUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *RelaySiteGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RelaySiteGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelaySiteGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelaySiteGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
