// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/relaysite"
	"github.com/looplj/axonhub/internal/ent/relaysiteannouncement"
	"github.com/looplj/axonhub/internal/objects"
)

// RelaySiteAnnouncement is the model entity for the RelaySiteAnnouncement schema.
type RelaySiteAnnouncement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RelaySiteID holds the value of the "relay_site_id" field.
	RelaySiteID int `json:"relay_site_id,omitempty"`
	// RemoteID holds the value of the "remote_id" field.
	RemoteID string `json:"remote_id,omitempty"`
	// Type holds the value of the "type" field.
	Type *string `json:"type,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra *string `json:"extra,omitempty"`
	// ContentHash holds the value of the "content_hash" field.
	ContentHash string `json:"content_hash,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// FetchedAt holds the value of the "fetched_at" field.
	FetchedAt time.Time `json:"fetched_at,omitempty"`
	// ReadAt holds the value of the "read_at" field.
	ReadAt *time.Time `json:"read_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata objects.RelaySiteAnnouncementMetadata `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelaySiteAnnouncementQuery when eager-loading is set.
	Edges        RelaySiteAnnouncementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelaySiteAnnouncementEdges holds the relations/edges for other nodes in the graph.
type RelaySiteAnnouncementEdges struct {
	// RelaySite holds the value of the relay_site edge.
	RelaySite *RelaySite `json:"relay_site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// RelaySiteOrErr returns the RelaySite value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelaySiteAnnouncementEdges) RelaySiteOrErr() (*RelaySite, error) {
	if e.RelaySite != nil {
		return e.RelaySite, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: relaysite.Label}
	}
	return nil, &NotLoadedError{edge: "relay_site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelaySiteAnnouncement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relaysiteannouncement.FieldMetadata:
			values[i] = new([]byte)
		case relaysiteannouncement.FieldID, relaysiteannouncement.FieldRelaySiteID:
			values[i] = new(sql.NullInt64)
		case relaysiteannouncement.FieldRemoteID, relaysiteannouncement.FieldType, relaysiteannouncement.FieldContent, relaysiteannouncement.FieldExtra, relaysiteannouncement.FieldContentHash:
			values[i] = new(sql.NullString)
		case relaysiteannouncement.FieldCreatedAt, relaysiteannouncement.FieldUpdatedAt, relaysiteannouncement.FieldPublishedAt, relaysiteannouncement.FieldFetchedAt, relaysiteannouncement.FieldReadAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelaySiteAnnouncement fields.
func (_m *RelaySiteAnnouncement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relaysiteannouncement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relaysiteannouncement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relaysiteannouncement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relaysiteannouncement.FieldRelaySiteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field relay_site_id", values[i])
			} else if value.Valid {
				_m.RelaySiteID = int(value.Int64)
			}
		case relaysiteannouncement.FieldRemoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_id", values[i])
			} else if value.Valid {
				_m.RemoteID = value.String
			}
		case relaysiteannouncement.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = new(string)
				*_m.Type = value.String
			}
		case relaysiteannouncement.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case relaysiteannouncement.FieldExtra:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value.Valid {
				_m.Extra = new(string)
				*_m.Extra = value.String
			}
		case relaysiteannouncement.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case relaysiteannouncement.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case relaysiteannouncement.FieldFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fetched_at", values[i])
			} else if value.Valid {
				_m.FetchedAt = value.Time
			}
		case relaysiteannouncement.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = new(time.Time)
				*_m.ReadAt = value.Time
			}
		case relaysiteannouncement.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelaySiteAnnouncement.
// This includes values selected through modifiers, order, etc.
func (_m *RelaySiteAnnouncement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRelaySite queries the "relay_site" edge of the RelaySiteAnnouncement entity.
func (_m *RelaySiteAnnouncement) QueryRelaySite() *RelaySiteQuery {
	return NewRelaySiteAnnouncementClient(_m.config).QueryRelaySite(_m)
}

// Update returns a builder for updating this RelaySiteAnnouncement.
// Note that you need to call RelaySiteAnnouncement.Unwrap() before calling this method if this RelaySiteAnnouncement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelaySiteAnnouncement) Update() *RelaySiteAnnouncementUpdateOne {
	return NewRelaySiteAnnouncementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelaySiteAnnouncement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelaySiteAnnouncement) Unwrap() *RelaySiteAnnouncement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelaySiteAnnouncement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelaySiteAnnouncement) String() string {
	var builder strings.Builder
	builder.WriteString("RelaySiteAnnouncement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("relay_site_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelaySiteID))
	builder.WriteString(", ")
	builder.WriteString("remote_id=")
	builder.WriteString(_m.RemoteID)
	builder.WriteString(", ")
	if v := _m.Type; v != nil {
		builder.WriteString("type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	if v := _m.Extra; v != nil {
		builder.WriteString("extra=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("fetched_at=")
	builder.WriteString(_m.FetchedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ReadAt; v != nil {
		builder.WriteString("read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// RelaySiteAnnouncements is a parsable slice of RelaySiteAnnouncement.
type RelaySiteAnnouncements []*RelaySiteAnnouncement
