// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/relaysiteapikey"
	"github.com/looplj/axonhub/internal/objects"
)

// RelaySiteAPIKeyUpdate is the builder for updating RelaySiteAPIKey entities.
type RelaySiteAPIKeyUpdate struct {
	config
	hooks     []Hook
	mutation  *RelaySiteAPIKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RelaySiteAPIKeyUpdate builder.
func (_u *RelaySiteAPIKeyUpdate) Where(ps ...predicate.RelaySiteAPIKey) *RelaySiteAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelaySiteAPIKeyUpdate) SetUpdatedAt(v time.Time) *RelaySiteAPIKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RelaySiteAPIKeyUpdate) SetDeletedAt(v int) *RelaySiteAPIKeyUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableDeletedAt(v *int) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *RelaySiteAPIKeyUpdate) AddDeletedAt(v int) *RelaySiteAPIKeyUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RelaySiteAPIKeyUpdate) SetName(v string) *RelaySiteAPIKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableName(v *string) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *RelaySiteAPIKeyUpdate) ClearName() *RelaySiteAPIKeyUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RelaySiteAPIKeyUpdate) SetStatus(v relaysiteapikey.Status) *RelaySiteAPIKeyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableStatus(v *relaysiteapikey.Status) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *RelaySiteAPIKeyUpdate) SetGroupName(v string) *RelaySiteAPIKeyUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableGroupName(v *string) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *RelaySiteAPIKeyUpdate) ClearGroupName() *RelaySiteAPIKeyUpdate {
	_u.mutation.ClearGroupName()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *RelaySiteAPIKeyUpdate) SetQuota(v float64) *RelaySiteAPIKeyUpdate {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableQuota(v *float64) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *RelaySiteAPIKeyUpdate) AddQuota(v float64) *RelaySiteAPIKeyUpdate {
	_u.mutation.AddQuota(v)
	return _u
}

// ClearQuota clears the value of the "quota" field.
func (_u *RelaySiteAPIKeyUpdate) ClearQuota() *RelaySiteAPIKeyUpdate {
	_u.mutation.ClearQuota()
	return _u
}

// SetUsedQuota sets the "used_quota" field.
func (_u *RelaySiteAPIKeyUpdate) SetUsedQuota(v float64) *RelaySiteAPIKeyUpdate {
	_u.mutation.ResetUsedQuota()
	_u.mutation.SetUsedQuota(v)
	return _u
}

// SetNillableUsedQuota sets the "used_quota" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableUsedQuota(v *float64) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetUsedQuota(*v)
	}
	return _u
}

// AddUsedQuota adds value to the "used_quota" field.
func (_u *RelaySiteAPIKeyUpdate) AddUsedQuota(v float64) *RelaySiteAPIKeyUpdate {
	_u.mutation.AddUsedQuota(v)
	return _u
}

// ClearUsedQuota clears the value of the "used_quota" field.
func (_u *RelaySiteAPIKeyUpdate) ClearUsedQuota() *RelaySiteAPIKeyUpdate {
	_u.mutation.ClearUsedQuota()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RelaySiteAPIKeyUpdate) SetExpiresAt(v time.Time) *RelaySiteAPIKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableExpiresAt(v *time.Time) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RelaySiteAPIKeyUpdate) ClearExpiresAt() *RelaySiteAPIKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RelaySiteAPIKeyUpdate) SetMetadata(v objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableMetadata(v *objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RelaySiteAPIKeyUpdate) ClearMetadata() *RelaySiteAPIKeyUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *RelaySiteAPIKeyUpdate) SetSyncedAt(v time.Time) *RelaySiteAPIKeyUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdate) SetNillableSyncedAt(v *time.Time) *RelaySiteAPIKeyUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the RelaySiteAPIKeyMutation object of the builder.
func (_u *RelaySiteAPIKeyUpdate) Mutation() *RelaySiteAPIKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelaySiteAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelaySiteAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelaySiteAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelaySiteAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelaySiteAPIKeyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaysiteapikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysiteapikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaysiteapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelaySiteAPIKeyUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := relaysiteapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RelaySiteAPIKey.status": %w`, err)}
		}
	}
	if _u.mutation.RelaySiteCleared() && len(_u.mutation.RelaySiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelaySiteAPIKey.relay_site"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelaySiteAPIKeyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelaySiteAPIKeyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelaySiteAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaysiteapikey.Table, relaysiteapikey.Columns, sqlgraph.NewFieldSpec(relaysiteapikey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(relaysiteapikey.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaysiteapikey.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(relaysiteapikey.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(relaysiteapikey.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(relaysiteapikey.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(relaysiteapikey.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(relaysiteapikey.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(relaysiteapikey.FieldQuota, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaCleared() {
		_spec.ClearField(relaysiteapikey.FieldQuota, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UsedQuota(); ok {
		_spec.SetField(relaysiteapikey.FieldUsedQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedQuota(); ok {
		_spec.AddField(relaysiteapikey.FieldUsedQuota, field.TypeFloat64, value)
	}
	if _u.mutation.UsedQuotaCleared() {
		_spec.ClearField(relaysiteapikey.FieldUsedQuota, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(relaysiteapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(relaysiteapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(relaysiteapikey.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(relaysiteapikey.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldSyncedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaysiteapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelaySiteAPIKeyUpdateOne is the builder for updating a single RelaySiteAPIKey entity.
type RelaySiteAPIKeyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RelaySiteAPIKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetUpdatedAt(v time.Time) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetDeletedAt(v int) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableDeletedAt(v *int) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *RelaySiteAPIKeyUpdateOne) AddDeletedAt(v int) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetName(v string) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableName(v *string) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *RelaySiteAPIKeyUpdateOne) ClearName() *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetStatus(v relaysiteapikey.Status) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableStatus(v *relaysiteapikey.Status) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetGroupName(v string) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableGroupName(v *string) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *RelaySiteAPIKeyUpdateOne) ClearGroupName() *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ClearGroupName()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetQuota(v float64) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableQuota(v *float64) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *RelaySiteAPIKeyUpdateOne) AddQuota(v float64) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.AddQuota(v)
	return _u
}

// ClearQuota clears the value of the "quota" field.
func (_u *RelaySiteAPIKeyUpdateOne) ClearQuota() *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ClearQuota()
	return _u
}

// SetUsedQuota sets the "used_quota" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetUsedQuota(v float64) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ResetUsedQuota()
	_u.mutation.SetUsedQuota(v)
	return _u
}

// SetNillableUsedQuota sets the "used_quota" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableUsedQuota(v *float64) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetUsedQuota(*v)
	}
	return _u
}

// AddUsedQuota adds value to the "used_quota" field.
func (_u *RelaySiteAPIKeyUpdateOne) AddUsedQuota(v float64) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.AddUsedQuota(v)
	return _u
}

// ClearUsedQuota clears the value of the "used_quota" field.
func (_u *RelaySiteAPIKeyUpdateOne) ClearUsedQuota() *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ClearUsedQuota()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetExpiresAt(v time.Time) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RelaySiteAPIKeyUpdateOne) ClearExpiresAt() *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetMetadata(v objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableMetadata(v *objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RelaySiteAPIKeyUpdateOne) ClearMetadata() *RelaySiteAPIKeyUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *RelaySiteAPIKeyUpdateOne) SetSyncedAt(v time.Time) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *RelaySiteAPIKeyUpdateOne) SetNillableSyncedAt(v *time.Time) *RelaySiteAPIKeyUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the RelaySiteAPIKeyMutation object of the builder.
func (_u *RelaySiteAPIKeyUpdateOne) Mutation() *RelaySiteAPIKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the RelaySiteAPIKeyUpdate builder.
func (_u *RelaySiteAPIKeyUpdateOne) Where(ps ...predicate.RelaySiteAPIKey) *RelaySiteAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelaySiteAPIKeyUpdateOne) Select(field string, fields ...string) *RelaySiteAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelaySiteAPIKey entity.
func (_u *RelaySiteAPIKeyUpdateOne) Save(ctx context.Context) (*RelaySiteAPIKey, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelaySiteAPIKeyUpdateOne) SaveX(ctx context.Context) *RelaySiteAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelaySiteAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelaySiteAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelaySiteAPIKeyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaysiteapikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysiteapikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaysiteapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelaySiteAPIKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := relaysiteapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RelaySiteAPIKey.status": %w`, err)}
		}
	}
	if _u.mutation.RelaySiteCleared() && len(_u.mutation.RelaySiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelaySiteAPIKey.relay_site"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelaySiteAPIKeyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelaySiteAPIKeyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelaySiteAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *RelaySiteAPIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaysiteapikey.Table, relaysiteapikey.Columns, sqlgraph.NewFieldSpec(relaysiteapikey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelaySiteAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaysiteapikey.FieldID)
		for _, f := range fields {
			if !relaysiteapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relaysiteapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(relaysiteapikey.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaysiteapikey.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(relaysiteapikey.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(relaysiteapikey.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(relaysiteapikey.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(relaysiteapikey.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(relaysiteapikey.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(relaysiteapikey.FieldQuota, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaCleared() {
		_spec.ClearField(relaysiteapikey.FieldQuota, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UsedQuota(); ok {
		_spec.SetField(relaysiteapikey.FieldUsedQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedQuota(); ok {
		_spec.AddField(relaysiteapikey.FieldUsedQuota, field.TypeFloat64, value)
	}
	if _u.mutation.UsedQuotaCleared() {
		_spec.ClearField(relaysiteapikey.FieldUsedQuota, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(relaysiteapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(relaysiteapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(relaysiteapikey.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(relaysiteapikey.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldSyncedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RelaySiteAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaysiteapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
