// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/relaysitecheckinlog"
)

// RelaySiteCheckinLogUpdate is the builder for updating RelaySiteCheckinLog entities.
type RelaySiteCheckinLogUpdate struct {
	config
	hooks     []Hook
	mutation  *RelaySiteCheckinLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RelaySiteCheckinLogUpdate builder.
func (_u *RelaySiteCheckinLogUpdate) Where(ps ...predicate.RelaySiteCheckinLog) *RelaySiteCheckinLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelaySiteCheckinLogUpdate) SetUpdatedAt(v time.Time) *RelaySiteCheckinLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *RelaySiteCheckinLogUpdate) SetExecutedAt(v time.Time) *RelaySiteCheckinLogUpdate {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdate) SetNillableExecutedAt(v *time.Time) *RelaySiteCheckinLogUpdate {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RelaySiteCheckinLogUpdate) SetStatus(v relaysitecheckinlog.Status) *RelaySiteCheckinLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdate) SetNillableStatus(v *relaysitecheckinlog.Status) *RelaySiteCheckinLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *RelaySiteCheckinLogUpdate) SetMessage(v string) *RelaySiteCheckinLogUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdate) SetNillableMessage(v *string) *RelaySiteCheckinLogUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *RelaySiteCheckinLogUpdate) ClearMessage() *RelaySiteCheckinLogUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RelaySiteCheckinLogUpdate) SetErrorMessage(v string) *RelaySiteCheckinLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdate) SetNillableErrorMessage(v *string) *RelaySiteCheckinLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RelaySiteCheckinLogUpdate) ClearErrorMessage() *RelaySiteCheckinLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the RelaySiteCheckinLogMutation object of the builder.
func (_u *RelaySiteCheckinLogUpdate) Mutation() *RelaySiteCheckinLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelaySiteCheckinLogUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelaySiteCheckinLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelaySiteCheckinLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelaySiteCheckinLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelaySiteCheckinLogUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaysitecheckinlog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysitecheckinlog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaysitecheckinlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelaySiteCheckinLogUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := relaysitecheckinlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RelaySiteCheckinLog.status": %w`, err)}
		}
	}
	if _u.mutation.RelaySiteCleared() && len(_u.mutation.RelaySiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelaySiteCheckinLog.relay_site"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelaySiteCheckinLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelaySiteCheckinLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelaySiteCheckinLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaysitecheckinlog.Table, relaysitecheckinlog.Columns, sqlgraph.NewFieldSpec(relaysitecheckinlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaysitecheckinlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(relaysitecheckinlog.FieldExecutedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(relaysitecheckinlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(relaysitecheckinlog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(relaysitecheckinlog.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(relaysitecheckinlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(relaysitecheckinlog.FieldErrorMessage, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaysitecheckinlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelaySiteCheckinLogUpdateOne is the builder for updating a single RelaySiteCheckinLog entity.
type RelaySiteCheckinLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RelaySiteCheckinLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelaySiteCheckinLogUpdateOne) SetUpdatedAt(v time.Time) *RelaySiteCheckinLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *RelaySiteCheckinLogUpdateOne) SetExecutedAt(v time.Time) *RelaySiteCheckinLogUpdateOne {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdateOne) SetNillableExecutedAt(v *time.Time) *RelaySiteCheckinLogUpdateOne {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RelaySiteCheckinLogUpdateOne) SetStatus(v relaysitecheckinlog.Status) *RelaySiteCheckinLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdateOne) SetNillableStatus(v *relaysitecheckinlog.Status) *RelaySiteCheckinLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *RelaySiteCheckinLogUpdateOne) SetMessage(v string) *RelaySiteCheckinLogUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdateOne) SetNillableMessage(v *string) *RelaySiteCheckinLogUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *RelaySiteCheckinLogUpdateOne) ClearMessage() *RelaySiteCheckinLogUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RelaySiteCheckinLogUpdateOne) SetErrorMessage(v string) *RelaySiteCheckinLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RelaySiteCheckinLogUpdateOne) SetNillableErrorMessage(v *string) *RelaySiteCheckinLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RelaySiteCheckinLogUpdateOne) ClearErrorMessage() *RelaySiteCheckinLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the RelaySiteCheckinLogMutation object of the builder.
func (_u *RelaySiteCheckinLogUpdateOne) Mutation() *RelaySiteCheckinLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RelaySiteCheckinLogUpdate builder.
func (_u *RelaySiteCheckinLogUpdateOne) Where(ps ...predicate.RelaySiteCheckinLog) *RelaySiteCheckinLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelaySiteCheckinLogUpdateOne) Select(field string, fields ...string) *RelaySiteCheckinLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelaySiteCheckinLog entity.
func (_u *RelaySiteCheckinLogUpdateOne) Save(ctx context.Context) (*RelaySiteCheckinLog, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelaySiteCheckinLogUpdateOne) SaveX(ctx context.Context) *RelaySiteCheckinLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelaySiteCheckinLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelaySiteCheckinLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelaySiteCheckinLogUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaysitecheckinlog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysitecheckinlog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaysitecheckinlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelaySiteCheckinLogUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := relaysitecheckinlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RelaySiteCheckinLog.status": %w`, err)}
		}
	}
	if _u.mutation.RelaySiteCleared() && len(_u.mutation.RelaySiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelaySiteCheckinLog.relay_site"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelaySiteCheckinLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelaySiteCheckinLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelaySiteCheckinLogUpdateOne) sqlSave(ctx context.Context) (_node *RelaySiteCheckinLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaysitecheckinlog.Table, relaysitecheckinlog.Columns, sqlgraph.NewFieldSpec(relaysitecheckinlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelaySiteCheckinLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaysitecheckinlog.FieldID)
		for _, f := range fields {
			if !relaysitecheckinlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relaysitecheckinlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaysitecheckinlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(relaysitecheckinlog.FieldExecutedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(relaysitecheckinlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(relaysitecheckinlog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(relaysitecheckinlog.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(relaysitecheckinlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(relaysitecheckinlog.FieldErrorMessage, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RelaySiteCheckinLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaysitecheckinlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
