// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/relaysite"
	"github.com/looplj/axonhub/internal/ent/relaysiteannouncement"
	"github.com/looplj/axonhub/internal/objects"
)

// RelaySiteAnnouncementCreate is the builder for creating a RelaySiteAnnouncement entity.
type RelaySiteAnnouncementCreate struct {
	config
	mutation *RelaySiteAnnouncementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelaySiteAnnouncementCreate) SetCreatedAt(v time.Time) *RelaySiteAnnouncementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelaySiteAnnouncementCreate) SetNillableCreatedAt(v *time.Time) *RelaySiteAnnouncementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelaySiteAnnouncementCreate) SetUpdatedAt(v time.Time) *RelaySiteAnnouncementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelaySiteAnnouncementCreate) SetNillableUpdatedAt(v *time.Time) *RelaySiteAnnouncementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRelaySiteID sets the "relay_site_id" field.
func (_c *RelaySiteAnnouncementCreate) SetRelaySiteID(v int) *RelaySiteAnnouncementCreate {
	_c.mutation.SetRelaySiteID(v)
	return _c
}

// SetRemoteID sets the "remote_id" field.
func (_c *RelaySiteAnnouncementCreate) SetRemoteID(v string) *RelaySiteAnnouncementCreate {
	_c.mutation.SetRemoteID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *RelaySiteAnnouncementCreate) SetType(v string) *RelaySiteAnnouncementCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *RelaySiteAnnouncementCreate) SetNillableType(v *string) *RelaySiteAnnouncementCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *RelaySiteAnnouncementCreate) SetContent(v string) *RelaySiteAnnouncementCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetExtra sets the "extra" field.
func (_c *RelaySiteAnnouncementCreate) SetExtra(v string) *RelaySiteAnnouncementCreate {
	_c.mutation.SetExtra(v)
	return _c
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (_c *RelaySiteAnnouncementCreate) SetNillableExtra(v *string) *RelaySiteAnnouncementCreate {
	if v != nil {
		_c.SetExtra(*v)
	}
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *RelaySiteAnnouncementCreate) SetContentHash(v string) *RelaySiteAnnouncementCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *RelaySiteAnnouncementCreate) SetPublishedAt(v time.Time) *RelaySiteAnnouncementCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *RelaySiteAnnouncementCreate) SetNillablePublishedAt(v *time.Time) *RelaySiteAnnouncementCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetFetchedAt sets the "fetched_at" field.
func (_c *RelaySiteAnnouncementCreate) SetFetchedAt(v time.Time) *RelaySiteAnnouncementCreate {
	_c.mutation.SetFetchedAt(v)
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *RelaySiteAnnouncementCreate) SetReadAt(v time.Time) *RelaySiteAnnouncementCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *RelaySiteAnnouncementCreate) SetNillableReadAt(v *time.Time) *RelaySiteAnnouncementCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RelaySiteAnnouncementCreate) SetMetadata(v objects.RelaySiteAnnouncementMetadata) *RelaySiteAnnouncementCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *RelaySiteAnnouncementCreate) SetNillableMetadata(v *objects.RelaySiteAnnouncementMetadata) *RelaySiteAnnouncementCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetRelaySite sets the "relay_site" edge to the RelaySite entity.
func (_c *RelaySiteAnnouncementCreate) SetRelaySite(v *RelaySite) *RelaySiteAnnouncementCreate {
	return _c.SetRelaySiteID(v.ID)
}

// Mutation returns the RelaySiteAnnouncementMutation object of the builder.
func (_c *RelaySiteAnnouncementCreate) Mutation() *RelaySiteAnnouncementMutation {
	return _c.mutation
}

// Save creates the RelaySiteAnnouncement in the database.
func (_c *RelaySiteAnnouncementCreate) Save(ctx context.Context) (*RelaySiteAnnouncement, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelaySiteAnnouncementCreate) SaveX(ctx context.Context) *RelaySiteAnnouncement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelaySiteAnnouncementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelaySiteAnnouncementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelaySiteAnnouncementCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if relaysiteannouncement.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysiteannouncement.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := relaysiteannouncement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if relaysiteannouncement.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysiteannouncement.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaysiteannouncement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := relaysiteannouncement.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelaySiteAnnouncementCreate) check() error {
	if _, ok := _c.mutation.RelaySiteID(); !ok {
		return &ValidationError{Name: "relay_site_id", err: errors.New(`ent: missing required field "RelaySiteAnnouncement.relay_site_id"`)}
	}
	if _, ok := _c.mutation.RemoteID(); !ok {
		return &ValidationError{Name: "remote_id", err: errors.New(`ent: missing required field "RelaySiteAnnouncement.remote_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "RelaySiteAnnouncement.content"`)}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "RelaySiteAnnouncement.content_hash"`)}
	}
	if _, ok := _c.mutation.FetchedAt(); !ok {
		return &ValidationError{Name: "fetched_at", err: errors.New(`ent: missing required field "RelaySiteAnnouncement.fetched_at"`)}
	}
	if len(_c.mutation.RelaySiteIDs()) == 0 {
		return &ValidationError{Name: "relay_site", err: errors.New(`ent: missing required edge "RelaySiteAnnouncement.relay_site"`)}
	}
	return nil
}

func (_c *RelaySiteAnnouncementCreate) sqlSave(ctx context.Context) (*RelaySiteAnnouncement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelaySiteAnnouncementCreate) createSpec() (*RelaySiteAnnouncement, *sqlgraph.CreateSpec) {
	var (
		_node = &RelaySiteAnnouncement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relaysiteannouncement.Table, sqlgraph.NewFieldSpec(relaysiteannouncement.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relaysiteannouncement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relaysiteannouncement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RemoteID(); ok {
		_spec.SetField(relaysiteannouncement.FieldRemoteID, field.TypeString, value)
		_node.RemoteID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(relaysiteannouncement.FieldType, field.TypeString, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(relaysiteannouncement.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Extra(); ok {
		_spec.SetField(relaysiteannouncement.FieldExtra, field.TypeString, value)
		_node.Extra = &value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(relaysiteannouncement.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(relaysiteannouncement.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.FetchedAt(); ok {
		_spec.SetField(relaysiteannouncement.FieldFetchedAt, field.TypeTime, value)
		_node.FetchedAt = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(relaysiteannouncement.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(relaysiteannouncement.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.RelaySiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaysiteannouncement.RelaySiteTable,
			Columns: []string{relaysiteannouncement.RelaySiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaysite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RelaySiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelaySiteAnnouncement.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelaySiteAnnouncementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelaySiteAnnouncementCreate) OnConflict(opts ...sql.ConflictOption) *RelaySiteAnnouncementUpsertOne {
	_c.conflict = opts
	return &RelaySiteAnnouncementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelaySiteAnnouncement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelaySiteAnnouncementCreate) OnConflictColumns(columns ...string) *RelaySiteAnnouncementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelaySiteAnnouncementUpsertOne{
		create: _c,
	}
}

type (
	// RelaySiteAnnouncementUpsertOne is the builder for "upsert"-ing
	//  one RelaySiteAnnouncement node.
	RelaySiteAnnouncementUpsertOne struct {
		create *RelaySiteAnnouncementCreate
	}

	// RelaySiteAnnouncementUpsert is the "OnConflict" setter.
	RelaySiteAnnouncementUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteAnnouncementUpsert) SetUpdatedAt(v time.Time) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateUpdatedAt() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldUpdatedAt)
	return u
}

// SetRemoteID sets the "remote_id" field.
func (u *RelaySiteAnnouncementUpsert) SetRemoteID(v string) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldRemoteID, v)
	return u
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateRemoteID() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldRemoteID)
	return u
}

// SetType sets the "type" field.
func (u *RelaySiteAnnouncementUpsert) SetType(v string) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateType() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldType)
	return u
}

// ClearType clears the value of the "type" field.
func (u *RelaySiteAnnouncementUpsert) ClearType() *RelaySiteAnnouncementUpsert {
	u.SetNull(relaysiteannouncement.FieldType)
	return u
}

// SetContent sets the "content" field.
func (u *RelaySiteAnnouncementUpsert) SetContent(v string) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateContent() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldContent)
	return u
}

// SetExtra sets the "extra" field.
func (u *RelaySiteAnnouncementUpsert) SetExtra(v string) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldExtra, v)
	return u
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateExtra() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldExtra)
	return u
}

// ClearExtra clears the value of the "extra" field.
func (u *RelaySiteAnnouncementUpsert) ClearExtra() *RelaySiteAnnouncementUpsert {
	u.SetNull(relaysiteannouncement.FieldExtra)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *RelaySiteAnnouncementUpsert) SetContentHash(v string) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateContentHash() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldContentHash)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *RelaySiteAnnouncementUpsert) SetPublishedAt(v time.Time) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdatePublishedAt() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *RelaySiteAnnouncementUpsert) ClearPublishedAt() *RelaySiteAnnouncementUpsert {
	u.SetNull(relaysiteannouncement.FieldPublishedAt)
	return u
}

// SetFetchedAt sets the "fetched_at" field.
func (u *RelaySiteAnnouncementUpsert) SetFetchedAt(v time.Time) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldFetchedAt, v)
	return u
}

// UpdateFetchedAt sets the "fetched_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateFetchedAt() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldFetchedAt)
	return u
}

// SetReadAt sets the "read_at" field.
func (u *RelaySiteAnnouncementUpsert) SetReadAt(v time.Time) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldReadAt, v)
	return u
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateReadAt() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldReadAt)
	return u
}

// ClearReadAt clears the value of the "read_at" field.
func (u *RelaySiteAnnouncementUpsert) ClearReadAt() *RelaySiteAnnouncementUpsert {
	u.SetNull(relaysiteannouncement.FieldReadAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *RelaySiteAnnouncementUpsert) SetMetadata(v objects.RelaySiteAnnouncementMetadata) *RelaySiteAnnouncementUpsert {
	u.Set(relaysiteannouncement.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsert) UpdateMetadata() *RelaySiteAnnouncementUpsert {
	u.SetExcluded(relaysiteannouncement.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RelaySiteAnnouncementUpsert) ClearMetadata() *RelaySiteAnnouncementUpsert {
	u.SetNull(relaysiteannouncement.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RelaySiteAnnouncement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelaySiteAnnouncementUpsertOne) UpdateNewValues() *RelaySiteAnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(relaysiteannouncement.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.RelaySiteID(); exists {
			s.SetIgnore(relaysiteannouncement.FieldRelaySiteID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelaySiteAnnouncement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RelaySiteAnnouncementUpsertOne) Ignore() *RelaySiteAnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelaySiteAnnouncementUpsertOne) DoNothing() *RelaySiteAnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelaySiteAnnouncementCreate.OnConflict
// documentation for more info.
func (u *RelaySiteAnnouncementUpsertOne) Update(set func(*RelaySiteAnnouncementUpsert)) *RelaySiteAnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelaySiteAnnouncementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteAnnouncementUpsertOne) SetUpdatedAt(v time.Time) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateUpdatedAt() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRemoteID sets the "remote_id" field.
func (u *RelaySiteAnnouncementUpsertOne) SetRemoteID(v string) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetRemoteID(v)
	})
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateRemoteID() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateRemoteID()
	})
}

// SetType sets the "type" field.
func (u *RelaySiteAnnouncementUpsertOne) SetType(v string) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateType() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *RelaySiteAnnouncementUpsertOne) ClearType() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearType()
	})
}

// SetContent sets the "content" field.
func (u *RelaySiteAnnouncementUpsertOne) SetContent(v string) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateContent() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateContent()
	})
}

// SetExtra sets the "extra" field.
func (u *RelaySiteAnnouncementUpsertOne) SetExtra(v string) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateExtra() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateExtra()
	})
}

// ClearExtra clears the value of the "extra" field.
func (u *RelaySiteAnnouncementUpsertOne) ClearExtra() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearExtra()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *RelaySiteAnnouncementUpsertOne) SetContentHash(v string) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateContentHash() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateContentHash()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *RelaySiteAnnouncementUpsertOne) SetPublishedAt(v time.Time) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdatePublishedAt() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *RelaySiteAnnouncementUpsertOne) ClearPublishedAt() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearPublishedAt()
	})
}

// SetFetchedAt sets the "fetched_at" field.
func (u *RelaySiteAnnouncementUpsertOne) SetFetchedAt(v time.Time) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetFetchedAt(v)
	})
}

// UpdateFetchedAt sets the "fetched_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateFetchedAt() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateFetchedAt()
	})
}

// SetReadAt sets the "read_at" field.
func (u *RelaySiteAnnouncementUpsertOne) SetReadAt(v time.Time) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateReadAt() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateReadAt()
	})
}

// ClearReadAt clears the value of the "read_at" field.
func (u *RelaySiteAnnouncementUpsertOne) ClearReadAt() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearReadAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RelaySiteAnnouncementUpsertOne) SetMetadata(v objects.RelaySiteAnnouncementMetadata) *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertOne) UpdateMetadata() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RelaySiteAnnouncementUpsertOne) ClearMetadata() *RelaySiteAnnouncementUpsertOne {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *RelaySiteAnnouncementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelaySiteAnnouncementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelaySiteAnnouncementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RelaySiteAnnouncementUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RelaySiteAnnouncementUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RelaySiteAnnouncementCreateBulk is the builder for creating many RelaySiteAnnouncement entities in bulk.
type RelaySiteAnnouncementCreateBulk struct {
	config
	err      error
	builders []*RelaySiteAnnouncementCreate
	conflict []sql.ConflictOption
}

// Save creates the RelaySiteAnnouncement entities in the database.
func (_c *RelaySiteAnnouncementCreateBulk) Save(ctx context.Context) ([]*RelaySiteAnnouncement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelaySiteAnnouncement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelaySiteAnnouncementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelaySiteAnnouncementCreateBulk) SaveX(ctx context.Context) []*RelaySiteAnnouncement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelaySiteAnnouncementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelaySiteAnnouncementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelaySiteAnnouncement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelaySiteAnnouncementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelaySiteAnnouncementCreateBulk) OnConflict(opts ...sql.ConflictOption) *RelaySiteAnnouncementUpsertBulk {
	_c.conflict = opts
	return &RelaySiteAnnouncementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelaySiteAnnouncement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelaySiteAnnouncementCreateBulk) OnConflictColumns(columns ...string) *RelaySiteAnnouncementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelaySiteAnnouncementUpsertBulk{
		create: _c,
	}
}

// RelaySiteAnnouncementUpsertBulk is the builder for "upsert"-ing
// a bulk of RelaySiteAnnouncement nodes.
type RelaySiteAnnouncementUpsertBulk struct {
	create *RelaySiteAnnouncementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RelaySiteAnnouncement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelaySiteAnnouncementUpsertBulk) UpdateNewValues() *RelaySiteAnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(relaysiteannouncement.FieldCreatedAt)
			}
			if _, exists := b.mutation.RelaySiteID(); exists {
				s.SetIgnore(relaysiteannouncement.FieldRelaySiteID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelaySiteAnnouncement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RelaySiteAnnouncementUpsertBulk) Ignore() *RelaySiteAnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelaySiteAnnouncementUpsertBulk) DoNothing() *RelaySiteAnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelaySiteAnnouncementCreateBulk.OnConflict
// documentation for more info.
func (u *RelaySiteAnnouncementUpsertBulk) Update(set func(*RelaySiteAnnouncementUpsert)) *RelaySiteAnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelaySiteAnnouncementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetUpdatedAt(v time.Time) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateUpdatedAt() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRemoteID sets the "remote_id" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetRemoteID(v string) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetRemoteID(v)
	})
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateRemoteID() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateRemoteID()
	})
}

// SetType sets the "type" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetType(v string) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateType() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *RelaySiteAnnouncementUpsertBulk) ClearType() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearType()
	})
}

// SetContent sets the "content" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetContent(v string) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateContent() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateContent()
	})
}

// SetExtra sets the "extra" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetExtra(v string) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateExtra() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateExtra()
	})
}

// ClearExtra clears the value of the "extra" field.
func (u *RelaySiteAnnouncementUpsertBulk) ClearExtra() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearExtra()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetContentHash(v string) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateContentHash() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateContentHash()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetPublishedAt(v time.Time) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdatePublishedAt() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *RelaySiteAnnouncementUpsertBulk) ClearPublishedAt() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearPublishedAt()
	})
}

// SetFetchedAt sets the "fetched_at" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetFetchedAt(v time.Time) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetFetchedAt(v)
	})
}

// UpdateFetchedAt sets the "fetched_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateFetchedAt() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateFetchedAt()
	})
}

// SetReadAt sets the "read_at" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetReadAt(v time.Time) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateReadAt() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateReadAt()
	})
}

// ClearReadAt clears the value of the "read_at" field.
func (u *RelaySiteAnnouncementUpsertBulk) ClearReadAt() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearReadAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RelaySiteAnnouncementUpsertBulk) SetMetadata(v objects.RelaySiteAnnouncementMetadata) *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RelaySiteAnnouncementUpsertBulk) UpdateMetadata() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RelaySiteAnnouncementUpsertBulk) ClearMetadata() *RelaySiteAnnouncementUpsertBulk {
	return u.Update(func(s *RelaySiteAnnouncementUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *RelaySiteAnnouncementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RelaySiteAnnouncementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelaySiteAnnouncementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelaySiteAnnouncementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
