// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/relaysite"
	"github.com/looplj/axonhub/internal/ent/relaysiteapikey"
	"github.com/looplj/axonhub/internal/objects"
)

// RelaySiteAPIKeyCreate is the builder for creating a RelaySiteAPIKey entity.
type RelaySiteAPIKeyCreate struct {
	config
	mutation *RelaySiteAPIKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelaySiteAPIKeyCreate) SetCreatedAt(v time.Time) *RelaySiteAPIKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableCreatedAt(v *time.Time) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelaySiteAPIKeyCreate) SetUpdatedAt(v time.Time) *RelaySiteAPIKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableUpdatedAt(v *time.Time) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RelaySiteAPIKeyCreate) SetDeletedAt(v int) *RelaySiteAPIKeyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableDeletedAt(v *int) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetRelaySiteID sets the "relay_site_id" field.
func (_c *RelaySiteAPIKeyCreate) SetRelaySiteID(v int) *RelaySiteAPIKeyCreate {
	_c.mutation.SetRelaySiteID(v)
	return _c
}

// SetRemoteID sets the "remote_id" field.
func (_c *RelaySiteAPIKeyCreate) SetRemoteID(v string) *RelaySiteAPIKeyCreate {
	_c.mutation.SetRemoteID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RelaySiteAPIKeyCreate) SetName(v string) *RelaySiteAPIKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableName(v *string) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RelaySiteAPIKeyCreate) SetStatus(v relaysiteapikey.Status) *RelaySiteAPIKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableStatus(v *relaysiteapikey.Status) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *RelaySiteAPIKeyCreate) SetGroupName(v string) *RelaySiteAPIKeyCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableGroupName(v *string) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetGroupName(*v)
	}
	return _c
}

// SetQuota sets the "quota" field.
func (_c *RelaySiteAPIKeyCreate) SetQuota(v float64) *RelaySiteAPIKeyCreate {
	_c.mutation.SetQuota(v)
	return _c
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableQuota(v *float64) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetQuota(*v)
	}
	return _c
}

// SetUsedQuota sets the "used_quota" field.
func (_c *RelaySiteAPIKeyCreate) SetUsedQuota(v float64) *RelaySiteAPIKeyCreate {
	_c.mutation.SetUsedQuota(v)
	return _c
}

// SetNillableUsedQuota sets the "used_quota" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableUsedQuota(v *float64) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetUsedQuota(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RelaySiteAPIKeyCreate) SetExpiresAt(v time.Time) *RelaySiteAPIKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableExpiresAt(v *time.Time) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RelaySiteAPIKeyCreate) SetMetadata(v objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *RelaySiteAPIKeyCreate) SetNillableMetadata(v *objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *RelaySiteAPIKeyCreate) SetSyncedAt(v time.Time) *RelaySiteAPIKeyCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetRelaySite sets the "relay_site" edge to the RelaySite entity.
func (_c *RelaySiteAPIKeyCreate) SetRelaySite(v *RelaySite) *RelaySiteAPIKeyCreate {
	return _c.SetRelaySiteID(v.ID)
}

// Mutation returns the RelaySiteAPIKeyMutation object of the builder.
func (_c *RelaySiteAPIKeyCreate) Mutation() *RelaySiteAPIKeyMutation {
	return _c.mutation
}

// Save creates the RelaySiteAPIKey in the database.
func (_c *RelaySiteAPIKeyCreate) Save(ctx context.Context) (*RelaySiteAPIKey, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelaySiteAPIKeyCreate) SaveX(ctx context.Context) *RelaySiteAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelaySiteAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelaySiteAPIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelaySiteAPIKeyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if relaysiteapikey.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysiteapikey.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := relaysiteapikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if relaysiteapikey.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaysiteapikey.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaysiteapikey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := relaysiteapikey.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := relaysiteapikey.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := relaysiteapikey.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelaySiteAPIKeyCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "RelaySiteAPIKey.deleted_at"`)}
	}
	if _, ok := _c.mutation.RelaySiteID(); !ok {
		return &ValidationError{Name: "relay_site_id", err: errors.New(`ent: missing required field "RelaySiteAPIKey.relay_site_id"`)}
	}
	if _, ok := _c.mutation.RemoteID(); !ok {
		return &ValidationError{Name: "remote_id", err: errors.New(`ent: missing required field "RelaySiteAPIKey.remote_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RelaySiteAPIKey.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := relaysiteapikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RelaySiteAPIKey.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "RelaySiteAPIKey.synced_at"`)}
	}
	if len(_c.mutation.RelaySiteIDs()) == 0 {
		return &ValidationError{Name: "relay_site", err: errors.New(`ent: missing required edge "RelaySiteAPIKey.relay_site"`)}
	}
	return nil
}

func (_c *RelaySiteAPIKeyCreate) sqlSave(ctx context.Context) (*RelaySiteAPIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelaySiteAPIKeyCreate) createSpec() (*RelaySiteAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &RelaySiteAPIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relaysiteapikey.Table, sqlgraph.NewFieldSpec(relaysiteapikey.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.RemoteID(); ok {
		_spec.SetField(relaysiteapikey.FieldRemoteID, field.TypeString, value)
		_node.RemoteID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(relaysiteapikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(relaysiteapikey.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(relaysiteapikey.FieldGroupName, field.TypeString, value)
		_node.GroupName = &value
	}
	if value, ok := _c.mutation.Quota(); ok {
		_spec.SetField(relaysiteapikey.FieldQuota, field.TypeFloat64, value)
		_node.Quota = &value
	}
	if value, ok := _c.mutation.UsedQuota(); ok {
		_spec.SetField(relaysiteapikey.FieldUsedQuota, field.TypeFloat64, value)
		_node.UsedQuota = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(relaysiteapikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(relaysiteapikey.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(relaysiteapikey.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if nodes := _c.mutation.RelaySiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaysiteapikey.RelaySiteTable,
			Columns: []string{relaysiteapikey.RelaySiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaysite.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RelaySiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelaySiteAPIKey.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelaySiteAPIKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelaySiteAPIKeyCreate) OnConflict(opts ...sql.ConflictOption) *RelaySiteAPIKeyUpsertOne {
	_c.conflict = opts
	return &RelaySiteAPIKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelaySiteAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelaySiteAPIKeyCreate) OnConflictColumns(columns ...string) *RelaySiteAPIKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelaySiteAPIKeyUpsertOne{
		create: _c,
	}
}

type (
	// RelaySiteAPIKeyUpsertOne is the builder for "upsert"-ing
	//  one RelaySiteAPIKey node.
	RelaySiteAPIKeyUpsertOne struct {
		create *RelaySiteAPIKeyCreate
	}

	// RelaySiteAPIKeyUpsert is the "OnConflict" setter.
	RelaySiteAPIKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteAPIKeyUpsert) SetUpdatedAt(v time.Time) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateUpdatedAt() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RelaySiteAPIKeyUpsert) SetDeletedAt(v int) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateDeletedAt() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RelaySiteAPIKeyUpsert) AddDeletedAt(v int) *RelaySiteAPIKeyUpsert {
	u.Add(relaysiteapikey.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *RelaySiteAPIKeyUpsert) SetName(v string) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateName() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *RelaySiteAPIKeyUpsert) ClearName() *RelaySiteAPIKeyUpsert {
	u.SetNull(relaysiteapikey.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *RelaySiteAPIKeyUpsert) SetStatus(v relaysiteapikey.Status) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateStatus() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldStatus)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *RelaySiteAPIKeyUpsert) SetGroupName(v string) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateGroupName() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldGroupName)
	return u
}

// ClearGroupName clears the value of the "group_name" field.
func (u *RelaySiteAPIKeyUpsert) ClearGroupName() *RelaySiteAPIKeyUpsert {
	u.SetNull(relaysiteapikey.FieldGroupName)
	return u
}

// SetQuota sets the "quota" field.
func (u *RelaySiteAPIKeyUpsert) SetQuota(v float64) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldQuota, v)
	return u
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateQuota() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldQuota)
	return u
}

// AddQuota adds v to the "quota" field.
func (u *RelaySiteAPIKeyUpsert) AddQuota(v float64) *RelaySiteAPIKeyUpsert {
	u.Add(relaysiteapikey.FieldQuota, v)
	return u
}

// ClearQuota clears the value of the "quota" field.
func (u *RelaySiteAPIKeyUpsert) ClearQuota() *RelaySiteAPIKeyUpsert {
	u.SetNull(relaysiteapikey.FieldQuota)
	return u
}

// SetUsedQuota sets the "used_quota" field.
func (u *RelaySiteAPIKeyUpsert) SetUsedQuota(v float64) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldUsedQuota, v)
	return u
}

// UpdateUsedQuota sets the "used_quota" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateUsedQuota() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldUsedQuota)
	return u
}

// AddUsedQuota adds v to the "used_quota" field.
func (u *RelaySiteAPIKeyUpsert) AddUsedQuota(v float64) *RelaySiteAPIKeyUpsert {
	u.Add(relaysiteapikey.FieldUsedQuota, v)
	return u
}

// ClearUsedQuota clears the value of the "used_quota" field.
func (u *RelaySiteAPIKeyUpsert) ClearUsedQuota() *RelaySiteAPIKeyUpsert {
	u.SetNull(relaysiteapikey.FieldUsedQuota)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *RelaySiteAPIKeyUpsert) SetExpiresAt(v time.Time) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateExpiresAt() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RelaySiteAPIKeyUpsert) ClearExpiresAt() *RelaySiteAPIKeyUpsert {
	u.SetNull(relaysiteapikey.FieldExpiresAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *RelaySiteAPIKeyUpsert) SetMetadata(v objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateMetadata() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RelaySiteAPIKeyUpsert) ClearMetadata() *RelaySiteAPIKeyUpsert {
	u.SetNull(relaysiteapikey.FieldMetadata)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *RelaySiteAPIKeyUpsert) SetSyncedAt(v time.Time) *RelaySiteAPIKeyUpsert {
	u.Set(relaysiteapikey.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsert) UpdateSyncedAt() *RelaySiteAPIKeyUpsert {
	u.SetExcluded(relaysiteapikey.FieldSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RelaySiteAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelaySiteAPIKeyUpsertOne) UpdateNewValues() *RelaySiteAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(relaysiteapikey.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.RelaySiteID(); exists {
			s.SetIgnore(relaysiteapikey.FieldRelaySiteID)
		}
		if _, exists := u.create.mutation.RemoteID(); exists {
			s.SetIgnore(relaysiteapikey.FieldRemoteID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelaySiteAPIKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RelaySiteAPIKeyUpsertOne) Ignore() *RelaySiteAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelaySiteAPIKeyUpsertOne) DoNothing() *RelaySiteAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelaySiteAPIKeyCreate.OnConflict
// documentation for more info.
func (u *RelaySiteAPIKeyUpsertOne) Update(set func(*RelaySiteAPIKeyUpsert)) *RelaySiteAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelaySiteAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteAPIKeyUpsertOne) SetUpdatedAt(v time.Time) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateUpdatedAt() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RelaySiteAPIKeyUpsertOne) SetDeletedAt(v int) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RelaySiteAPIKeyUpsertOne) AddDeletedAt(v int) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateDeletedAt() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RelaySiteAPIKeyUpsertOne) SetName(v string) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateName() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *RelaySiteAPIKeyUpsertOne) ClearName() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearName()
	})
}

// SetStatus sets the "status" field.
func (u *RelaySiteAPIKeyUpsertOne) SetStatus(v relaysiteapikey.Status) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateStatus() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetGroupName sets the "group_name" field.
func (u *RelaySiteAPIKeyUpsertOne) SetGroupName(v string) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateGroupName() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *RelaySiteAPIKeyUpsertOne) ClearGroupName() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearGroupName()
	})
}

// SetQuota sets the "quota" field.
func (u *RelaySiteAPIKeyUpsertOne) SetQuota(v float64) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetQuota(v)
	})
}

// AddQuota adds v to the "quota" field.
func (u *RelaySiteAPIKeyUpsertOne) AddQuota(v float64) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.AddQuota(v)
	})
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateQuota() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateQuota()
	})
}

// ClearQuota clears the value of the "quota" field.
func (u *RelaySiteAPIKeyUpsertOne) ClearQuota() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearQuota()
	})
}

// SetUsedQuota sets the "used_quota" field.
func (u *RelaySiteAPIKeyUpsertOne) SetUsedQuota(v float64) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetUsedQuota(v)
	})
}

// AddUsedQuota adds v to the "used_quota" field.
func (u *RelaySiteAPIKeyUpsertOne) AddUsedQuota(v float64) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.AddUsedQuota(v)
	})
}

// UpdateUsedQuota sets the "used_quota" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateUsedQuota() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateUsedQuota()
	})
}

// ClearUsedQuota clears the value of the "used_quota" field.
func (u *RelaySiteAPIKeyUpsertOne) ClearUsedQuota() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearUsedQuota()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RelaySiteAPIKeyUpsertOne) SetExpiresAt(v time.Time) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateExpiresAt() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RelaySiteAPIKeyUpsertOne) ClearExpiresAt() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RelaySiteAPIKeyUpsertOne) SetMetadata(v objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateMetadata() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RelaySiteAPIKeyUpsertOne) ClearMetadata() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearMetadata()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *RelaySiteAPIKeyUpsertOne) SetSyncedAt(v time.Time) *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertOne) UpdateSyncedAt() *RelaySiteAPIKeyUpsertOne {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *RelaySiteAPIKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelaySiteAPIKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelaySiteAPIKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RelaySiteAPIKeyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RelaySiteAPIKeyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RelaySiteAPIKeyCreateBulk is the builder for creating many RelaySiteAPIKey entities in bulk.
type RelaySiteAPIKeyCreateBulk struct {
	config
	err      error
	builders []*RelaySiteAPIKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the RelaySiteAPIKey entities in the database.
func (_c *RelaySiteAPIKeyCreateBulk) Save(ctx context.Context) ([]*RelaySiteAPIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelaySiteAPIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelaySiteAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelaySiteAPIKeyCreateBulk) SaveX(ctx context.Context) []*RelaySiteAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelaySiteAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelaySiteAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelaySiteAPIKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelaySiteAPIKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelaySiteAPIKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *RelaySiteAPIKeyUpsertBulk {
	_c.conflict = opts
	return &RelaySiteAPIKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelaySiteAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelaySiteAPIKeyCreateBulk) OnConflictColumns(columns ...string) *RelaySiteAPIKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelaySiteAPIKeyUpsertBulk{
		create: _c,
	}
}

// RelaySiteAPIKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of RelaySiteAPIKey nodes.
type RelaySiteAPIKeyUpsertBulk struct {
	create *RelaySiteAPIKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RelaySiteAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelaySiteAPIKeyUpsertBulk) UpdateNewValues() *RelaySiteAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(relaysiteapikey.FieldCreatedAt)
			}
			if _, exists := b.mutation.RelaySiteID(); exists {
				s.SetIgnore(relaysiteapikey.FieldRelaySiteID)
			}
			if _, exists := b.mutation.RemoteID(); exists {
				s.SetIgnore(relaysiteapikey.FieldRemoteID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelaySiteAPIKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RelaySiteAPIKeyUpsertBulk) Ignore() *RelaySiteAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelaySiteAPIKeyUpsertBulk) DoNothing() *RelaySiteAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelaySiteAPIKeyCreateBulk.OnConflict
// documentation for more info.
func (u *RelaySiteAPIKeyUpsertBulk) Update(set func(*RelaySiteAPIKeyUpsert)) *RelaySiteAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelaySiteAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetUpdatedAt(v time.Time) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateUpdatedAt() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetDeletedAt(v int) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RelaySiteAPIKeyUpsertBulk) AddDeletedAt(v int) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateDeletedAt() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetName(v string) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateName() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *RelaySiteAPIKeyUpsertBulk) ClearName() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearName()
	})
}

// SetStatus sets the "status" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetStatus(v relaysiteapikey.Status) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateStatus() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetGroupName sets the "group_name" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetGroupName(v string) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateGroupName() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *RelaySiteAPIKeyUpsertBulk) ClearGroupName() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearGroupName()
	})
}

// SetQuota sets the "quota" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetQuota(v float64) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetQuota(v)
	})
}

// AddQuota adds v to the "quota" field.
func (u *RelaySiteAPIKeyUpsertBulk) AddQuota(v float64) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.AddQuota(v)
	})
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateQuota() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateQuota()
	})
}

// ClearQuota clears the value of the "quota" field.
func (u *RelaySiteAPIKeyUpsertBulk) ClearQuota() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearQuota()
	})
}

// SetUsedQuota sets the "used_quota" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetUsedQuota(v float64) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetUsedQuota(v)
	})
}

// AddUsedQuota adds v to the "used_quota" field.
func (u *RelaySiteAPIKeyUpsertBulk) AddUsedQuota(v float64) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.AddUsedQuota(v)
	})
}

// UpdateUsedQuota sets the "used_quota" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateUsedQuota() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateUsedQuota()
	})
}

// ClearUsedQuota clears the value of the "used_quota" field.
func (u *RelaySiteAPIKeyUpsertBulk) ClearUsedQuota() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearUsedQuota()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetExpiresAt(v time.Time) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateExpiresAt() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RelaySiteAPIKeyUpsertBulk) ClearExpiresAt() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetMetadata(v objects.RelaySiteAPIKeyMetadata) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateMetadata() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RelaySiteAPIKeyUpsertBulk) ClearMetadata() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.ClearMetadata()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *RelaySiteAPIKeyUpsertBulk) SetSyncedAt(v time.Time) *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *RelaySiteAPIKeyUpsertBulk) UpdateSyncedAt() *RelaySiteAPIKeyUpsertBulk {
	return u.Update(func(s *RelaySiteAPIKeyUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *RelaySiteAPIKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RelaySiteAPIKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelaySiteAPIKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelaySiteAPIKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
