// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/relaysite"
	"github.com/looplj/axonhub/internal/ent/relaysitecheckinlog"
)

// RelaySiteCheckinLog is the model entity for the RelaySiteCheckinLog schema.
type RelaySiteCheckinLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RelaySiteID holds the value of the "relay_site_id" field.
	RelaySiteID int `json:"relay_site_id,omitempty"`
	// ExecutedAt holds the value of the "executed_at" field.
	ExecutedAt time.Time `json:"executed_at,omitempty"`
	// Status holds the value of the "status" field.
	Status relaysitecheckinlog.Status `json:"status,omitempty"`
	// Message holds the value of the "message" field.
	Message *string `json:"message,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelaySiteCheckinLogQuery when eager-loading is set.
	Edges        RelaySiteCheckinLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelaySiteCheckinLogEdges holds the relations/edges for other nodes in the graph.
type RelaySiteCheckinLogEdges struct {
	// RelaySite holds the value of the relay_site edge.
	RelaySite *RelaySite `json:"relay_site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// RelaySiteOrErr returns the RelaySite value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelaySiteCheckinLogEdges) RelaySiteOrErr() (*RelaySite, error) {
	if e.RelaySite != nil {
		return e.RelaySite, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: relaysite.Label}
	}
	return nil, &NotLoadedError{edge: "relay_site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelaySiteCheckinLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relaysitecheckinlog.FieldID, relaysitecheckinlog.FieldRelaySiteID:
			values[i] = new(sql.NullInt64)
		case relaysitecheckinlog.FieldStatus, relaysitecheckinlog.FieldMessage, relaysitecheckinlog.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case relaysitecheckinlog.FieldCreatedAt, relaysitecheckinlog.FieldUpdatedAt, relaysitecheckinlog.FieldExecutedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelaySiteCheckinLog fields.
func (_m *RelaySiteCheckinLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relaysitecheckinlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relaysitecheckinlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relaysitecheckinlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relaysitecheckinlog.FieldRelaySiteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field relay_site_id", values[i])
			} else if value.Valid {
				_m.RelaySiteID = int(value.Int64)
			}
		case relaysitecheckinlog.FieldExecutedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field executed_at", values[i])
			} else if value.Valid {
				_m.ExecutedAt = value.Time
			}
		case relaysitecheckinlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = relaysitecheckinlog.Status(value.String)
			}
		case relaysitecheckinlog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = new(string)
				*_m.Message = value.String
			}
		case relaysitecheckinlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelaySiteCheckinLog.
// This includes values selected through modifiers, order, etc.
func (_m *RelaySiteCheckinLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRelaySite queries the "relay_site" edge of the RelaySiteCheckinLog entity.
func (_m *RelaySiteCheckinLog) QueryRelaySite() *RelaySiteQuery {
	return NewRelaySiteCheckinLogClient(_m.config).QueryRelaySite(_m)
}

// Update returns a builder for updating this RelaySiteCheckinLog.
// Note that you need to call RelaySiteCheckinLog.Unwrap() before calling this method if this RelaySiteCheckinLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelaySiteCheckinLog) Update() *RelaySiteCheckinLogUpdateOne {
	return NewRelaySiteCheckinLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelaySiteCheckinLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelaySiteCheckinLog) Unwrap() *RelaySiteCheckinLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelaySiteCheckinLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelaySiteCheckinLog) String() string {
	var builder strings.Builder
	builder.WriteString("RelaySiteCheckinLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("relay_site_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelaySiteID))
	builder.WriteString(", ")
	builder.WriteString("executed_at=")
	builder.WriteString(_m.ExecutedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.Message; v != nil {
		builder.WriteString("message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// RelaySiteCheckinLogs is a parsable slice of RelaySiteCheckinLog.
type RelaySiteCheckinLogs []*RelaySiteCheckinLog
