// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/relaysiteannouncement"
)

// RelaySiteAnnouncementDelete is the builder for deleting a RelaySiteAnnouncement entity.
type RelaySiteAnnouncementDelete struct {
	config
	hooks    []Hook
	mutation *RelaySiteAnnouncementMutation
}

// Where appends a list predicates to the RelaySiteAnnouncementDelete builder.
func (_d *RelaySiteAnnouncementDelete) Where(ps ...predicate.RelaySiteAnnouncement) *RelaySiteAnnouncementDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RelaySiteAnnouncementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelaySiteAnnouncementDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RelaySiteAnnouncementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(relaysiteannouncement.Table, sqlgraph.NewFieldSpec(relaysiteannouncement.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RelaySiteAnnouncementDeleteOne is the builder for deleting a single RelaySiteAnnouncement entity.
type RelaySiteAnnouncementDeleteOne struct {
	_d *RelaySiteAnnouncementDelete
}

// Where appends a list predicates to the RelaySiteAnnouncementDelete builder.
func (_d *RelaySiteAnnouncementDeleteOne) Where(ps ...predicate.RelaySiteAnnouncement) *RelaySiteAnnouncementDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RelaySiteAnnouncementDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{relaysiteannouncement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelaySiteAnnouncementDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
