// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/datastorage"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/objects"
)

// RequestExecution is the model entity for the RequestExecution schema.
type RequestExecution struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID int `json:"request_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// Data Storage ID that this request belongs to
	DataStorageID int `json:"data_storage_id,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// Format holds the value of the "format" field.
	Format string `json:"format,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody objects.JSONRawMessage `json:"request_body,omitempty"`
	// ResponseBody holds the value of the "response_body" field.
	ResponseBody objects.JSONRawMessage `json:"response_body,omitempty"`
	// ResponseChunks holds the value of the "response_chunks" field.
	ResponseChunks []objects.JSONRawMessage `json:"response_chunks,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// HTTP status code from the upstream provider
	ResponseStatusCode *int `json:"response_status_code,omitempty"`
	// Status holds the value of the "status" field.
	Status requestexecution.Status `json:"status,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// MetricsLatencyMs holds the value of the "metrics_latency_ms" field.
	MetricsLatencyMs *int64 `json:"metrics_latency_ms,omitempty"`
	// MetricsFirstTokenLatencyMs holds the value of the "metrics_first_token_latency_ms" field.
	MetricsFirstTokenLatencyMs *int64 `json:"metrics_first_token_latency_ms,omitempty"`
	// Reasoning/thinking duration in milliseconds
	MetricsReasoningDurationMs *int64 `json:"metrics_reasoning_duration_ms,omitempty"`
	// Request headers
	RequestHeaders objects.JSONRawMessage `json:"request_headers,omitempty"`
	// Actual upstream request URL sent to the provider
	RequestURL string `json:"request_url,omitempty"`
	// Whether pass-through was active for this execution attempt
	PassThroughApplied bool `json:"pass_through_applied,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestExecutionQuery when eager-loading is set.
	Edges        RequestExecutionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestExecutionEdges holds the relations/edges for other nodes in the graph.
type RequestExecutionEdges struct {
	// Request holds the value of the request edge.
	Request *Request `json:"request,omitempty"`
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// DataStorage holds the value of the data_storage edge.
	DataStorage *DataStorage `json:"data_storage,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestExecutionEdges) RequestOrErr() (*Request, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: request.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestExecutionEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// DataStorageOrErr returns the DataStorage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestExecutionEdges) DataStorageOrErr() (*DataStorage, error) {
	if e.DataStorage != nil {
		return e.DataStorage, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: datastorage.Label}
	}
	return nil, &NotLoadedError{edge: "data_storage"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestExecution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestexecution.FieldRequestBody, requestexecution.FieldResponseBody, requestexecution.FieldResponseChunks, requestexecution.FieldRequestHeaders:
			values[i] = new([]byte)
		case requestexecution.FieldStream, requestexecution.FieldPassThroughApplied:
			values[i] = new(sql.NullBool)
		case requestexecution.FieldID, requestexecution.FieldProjectID, requestexecution.FieldRequestID, requestexecution.FieldChannelID, requestexecution.FieldDataStorageID, requestexecution.FieldResponseStatusCode, requestexecution.FieldMetricsLatencyMs, requestexecution.FieldMetricsFirstTokenLatencyMs, requestexecution.FieldMetricsReasoningDurationMs:
			values[i] = new(sql.NullInt64)
		case requestexecution.FieldExternalID, requestexecution.FieldModelID, requestexecution.FieldFormat, requestexecution.FieldErrorMessage, requestexecution.FieldStatus, requestexecution.FieldRequestURL:
			values[i] = new(sql.NullString)
		case requestexecution.FieldCreatedAt, requestexecution.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestExecution fields.
func (_m *RequestExecution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestexecution.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case requestexecution.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case requestexecution.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case requestexecution.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case requestexecution.FieldRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = int(value.Int64)
			}
		case requestexecution.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case requestexecution.FieldDataStorageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field data_storage_id", values[i])
			} else if value.Valid {
				_m.DataStorageID = int(value.Int64)
			}
		case requestexecution.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case requestexecution.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case requestexecution.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = value.String
			}
		case requestexecution.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestBody); err != nil {
					return fmt.Errorf("unmarshal field request_body: %w", err)
				}
			}
		case requestexecution.FieldResponseBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseBody); err != nil {
					return fmt.Errorf("unmarshal field response_body: %w", err)
				}
			}
		case requestexecution.FieldResponseChunks:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_chunks", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseChunks); err != nil {
					return fmt.Errorf("unmarshal field response_chunks: %w", err)
				}
			}
		case requestexecution.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case requestexecution.FieldResponseStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_status_code", values[i])
			} else if value.Valid {
				_m.ResponseStatusCode = new(int)
				*_m.ResponseStatusCode = int(value.Int64)
			}
		case requestexecution.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = requestexecution.Status(value.String)
			}
		case requestexecution.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case requestexecution.FieldMetricsLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_latency_ms", values[i])
			} else if value.Valid {
				_m.MetricsLatencyMs = new(int64)
				*_m.MetricsLatencyMs = value.Int64
			}
		case requestexecution.FieldMetricsFirstTokenLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_first_token_latency_ms", values[i])
			} else if value.Valid {
				_m.MetricsFirstTokenLatencyMs = new(int64)
				*_m.MetricsFirstTokenLatencyMs = value.Int64
			}
		case requestexecution.FieldMetricsReasoningDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_reasoning_duration_ms", values[i])
			} else if value.Valid {
				_m.MetricsReasoningDurationMs = new(int64)
				*_m.MetricsReasoningDurationMs = value.Int64
			}
		case requestexecution.FieldRequestHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestHeaders); err != nil {
					return fmt.Errorf("unmarshal field request_headers: %w", err)
				}
			}
		case requestexecution.FieldRequestURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_url", values[i])
			} else if value.Valid {
				_m.RequestURL = value.String
			}
		case requestexecution.FieldPassThroughApplied:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pass_through_applied", values[i])
			} else if value.Valid {
				_m.PassThroughApplied = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestExecution.
// This includes values selected through modifiers, order, etc.
func (_m *RequestExecution) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequest queries the "request" edge of the RequestExecution entity.
func (_m *RequestExecution) QueryRequest() *RequestQuery {
	return NewRequestExecutionClient(_m.config).QueryRequest(_m)
}

// QueryChannel queries the "channel" edge of the RequestExecution entity.
func (_m *RequestExecution) QueryChannel() *ChannelQuery {
	return NewRequestExecutionClient(_m.config).QueryChannel(_m)
}

// QueryDataStorage queries the "data_storage" edge of the RequestExecution entity.
func (_m *RequestExecution) QueryDataStorage() *DataStorageQuery {
	return NewRequestExecutionClient(_m.config).QueryDataStorage(_m)
}

// Update returns a builder for updating this RequestExecution.
// Note that you need to call RequestExecution.Unwrap() before calling this method if this RequestExecution
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestExecution) Update() *RequestExecutionUpdateOne {
	return NewRequestExecutionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestExecution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestExecution) Unwrap() *RequestExecution {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestExecution is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestExecution) String() string {
	var builder strings.Builder
	builder.WriteString("RequestExecution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("data_storage_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DataStorageID))
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(_m.Format)
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBody))
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBody))
	builder.WriteString(", ")
	builder.WriteString("response_chunks=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseChunks))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	if v := _m.ResponseStatusCode; v != nil {
		builder.WriteString("response_status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	if v := _m.MetricsLatencyMs; v != nil {
		builder.WriteString("metrics_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MetricsFirstTokenLatencyMs; v != nil {
		builder.WriteString("metrics_first_token_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MetricsReasoningDurationMs; v != nil {
		builder.WriteString("metrics_reasoning_duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestHeaders))
	builder.WriteString(", ")
	builder.WriteString("request_url=")
	builder.WriteString(_m.RequestURL)
	builder.WriteString(", ")
	builder.WriteString("pass_through_applied=")
	builder.WriteString(fmt.Sprintf("%v", _m.PassThroughApplied))
	builder.WriteByte(')')
	return builder.String()
}

// RequestExecutions is a parsable slice of RequestExecution.
type RequestExecutions []*RequestExecution
