// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/objects"
)

// RequestExecutionUpdate is the builder for updating RequestExecution entities.
type RequestExecutionUpdate struct {
	config
	hooks     []Hook
	mutation  *RequestExecutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RequestExecutionUpdate builder.
func (_u *RequestExecutionUpdate) Where(ps ...predicate.RequestExecution) *RequestExecutionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestExecutionUpdate) SetUpdatedAt(v time.Time) *RequestExecutionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *RequestExecutionUpdate) SetExternalID(v string) *RequestExecutionUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableExternalID(v *string) *RequestExecutionUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *RequestExecutionUpdate) ClearExternalID() *RequestExecutionUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestExecutionUpdate) SetResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// AppendResponseBody appends value to the "response_body" field.
func (_u *RequestExecutionUpdate) AppendResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.AppendResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestExecutionUpdate) ClearResponseBody() *RequestExecutionUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseChunks sets the "response_chunks" field.
func (_u *RequestExecutionUpdate) SetResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.SetResponseChunks(v)
	return _u
}

// AppendResponseChunks appends value to the "response_chunks" field.
func (_u *RequestExecutionUpdate) AppendResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.AppendResponseChunks(v)
	return _u
}

// ClearResponseChunks clears the value of the "response_chunks" field.
func (_u *RequestExecutionUpdate) ClearResponseChunks() *RequestExecutionUpdate {
	_u.mutation.ClearResponseChunks()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestExecutionUpdate) SetErrorMessage(v string) *RequestExecutionUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableErrorMessage(v *string) *RequestExecutionUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestExecutionUpdate) ClearErrorMessage() *RequestExecutionUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetResponseStatusCode sets the "response_status_code" field.
func (_u *RequestExecutionUpdate) SetResponseStatusCode(v int) *RequestExecutionUpdate {
	_u.mutation.ResetResponseStatusCode()
	_u.mutation.SetResponseStatusCode(v)
	return _u
}

// SetNillableResponseStatusCode sets the "response_status_code" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableResponseStatusCode(v *int) *RequestExecutionUpdate {
	if v != nil {
		_u.SetResponseStatusCode(*v)
	}
	return _u
}

// AddResponseStatusCode adds value to the "response_status_code" field.
func (_u *RequestExecutionUpdate) AddResponseStatusCode(v int) *RequestExecutionUpdate {
	_u.mutation.AddResponseStatusCode(v)
	return _u
}

// ClearResponseStatusCode clears the value of the "response_status_code" field.
func (_u *RequestExecutionUpdate) ClearResponseStatusCode() *RequestExecutionUpdate {
	_u.mutation.ClearResponseStatusCode()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestExecutionUpdate) SetStatus(v requestexecution.Status) *RequestExecutionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableStatus(v *requestexecution.Status) *RequestExecutionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetricsLatencyMs sets the "metrics_latency_ms" field.
func (_u *RequestExecutionUpdate) SetMetricsLatencyMs(v int64) *RequestExecutionUpdate {
	_u.mutation.ResetMetricsLatencyMs()
	_u.mutation.SetMetricsLatencyMs(v)
	return _u
}

// SetNillableMetricsLatencyMs sets the "metrics_latency_ms" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableMetricsLatencyMs(v *int64) *RequestExecutionUpdate {
	if v != nil {
		_u.SetMetricsLatencyMs(*v)
	}
	return _u
}

// AddMetricsLatencyMs adds value to the "metrics_latency_ms" field.
func (_u *RequestExecutionUpdate) AddMetricsLatencyMs(v int64) *RequestExecutionUpdate {
	_u.mutation.AddMetricsLatencyMs(v)
	return _u
}

// ClearMetricsLatencyMs clears the value of the "metrics_latency_ms" field.
func (_u *RequestExecutionUpdate) ClearMetricsLatencyMs() *RequestExecutionUpdate {
	_u.mutation.ClearMetricsLatencyMs()
	return _u
}

// SetMetricsFirstTokenLatencyMs sets the "metrics_first_token_latency_ms" field.
func (_u *RequestExecutionUpdate) SetMetricsFirstTokenLatencyMs(v int64) *RequestExecutionUpdate {
	_u.mutation.ResetMetricsFirstTokenLatencyMs()
	_u.mutation.SetMetricsFirstTokenLatencyMs(v)
	return _u
}

// SetNillableMetricsFirstTokenLatencyMs sets the "metrics_first_token_latency_ms" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableMetricsFirstTokenLatencyMs(v *int64) *RequestExecutionUpdate {
	if v != nil {
		_u.SetMetricsFirstTokenLatencyMs(*v)
	}
	return _u
}

// AddMetricsFirstTokenLatencyMs adds value to the "metrics_first_token_latency_ms" field.
func (_u *RequestExecutionUpdate) AddMetricsFirstTokenLatencyMs(v int64) *RequestExecutionUpdate {
	_u.mutation.AddMetricsFirstTokenLatencyMs(v)
	return _u
}

// ClearMetricsFirstTokenLatencyMs clears the value of the "metrics_first_token_latency_ms" field.
func (_u *RequestExecutionUpdate) ClearMetricsFirstTokenLatencyMs() *RequestExecutionUpdate {
	_u.mutation.ClearMetricsFirstTokenLatencyMs()
	return _u
}

// SetMetricsReasoningDurationMs sets the "metrics_reasoning_duration_ms" field.
func (_u *RequestExecutionUpdate) SetMetricsReasoningDurationMs(v int64) *RequestExecutionUpdate {
	_u.mutation.ResetMetricsReasoningDurationMs()
	_u.mutation.SetMetricsReasoningDurationMs(v)
	return _u
}

// SetNillableMetricsReasoningDurationMs sets the "metrics_reasoning_duration_ms" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableMetricsReasoningDurationMs(v *int64) *RequestExecutionUpdate {
	if v != nil {
		_u.SetMetricsReasoningDurationMs(*v)
	}
	return _u
}

// AddMetricsReasoningDurationMs adds value to the "metrics_reasoning_duration_ms" field.
func (_u *RequestExecutionUpdate) AddMetricsReasoningDurationMs(v int64) *RequestExecutionUpdate {
	_u.mutation.AddMetricsReasoningDurationMs(v)
	return _u
}

// ClearMetricsReasoningDurationMs clears the value of the "metrics_reasoning_duration_ms" field.
func (_u *RequestExecutionUpdate) ClearMetricsReasoningDurationMs() *RequestExecutionUpdate {
	_u.mutation.ClearMetricsReasoningDurationMs()
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *RequestExecutionUpdate) SetRequestHeaders(v objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// AppendRequestHeaders appends value to the "request_headers" field.
func (_u *RequestExecutionUpdate) AppendRequestHeaders(v objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.AppendRequestHeaders(v)
	return _u
}

// ClearRequestHeaders clears the value of the "request_headers" field.
func (_u *RequestExecutionUpdate) ClearRequestHeaders() *RequestExecutionUpdate {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// SetRequestURL sets the "request_url" field.
func (_u *RequestExecutionUpdate) SetRequestURL(v string) *RequestExecutionUpdate {
	_u.mutation.SetRequestURL(v)
	return _u
}

// SetNillableRequestURL sets the "request_url" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableRequestURL(v *string) *RequestExecutionUpdate {
	if v != nil {
		_u.SetRequestURL(*v)
	}
	return _u
}

// ClearRequestURL clears the value of the "request_url" field.
func (_u *RequestExecutionUpdate) ClearRequestURL() *RequestExecutionUpdate {
	_u.mutation.ClearRequestURL()
	return _u
}

// SetPassThroughApplied sets the "pass_through_applied" field.
func (_u *RequestExecutionUpdate) SetPassThroughApplied(v bool) *RequestExecutionUpdate {
	_u.mutation.SetPassThroughApplied(v)
	return _u
}

// SetNillablePassThroughApplied sets the "pass_through_applied" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillablePassThroughApplied(v *bool) *RequestExecutionUpdate {
	if v != nil {
		_u.SetPassThroughApplied(*v)
	}
	return _u
}

// Mutation returns the RequestExecutionMutation object of the builder.
func (_u *RequestExecutionUpdate) Mutation() *RequestExecutionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestExecutionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestExecutionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestExecutionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestExecutionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestExecutionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestexecution.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestExecutionUpdate) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := requestexecution.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "RequestExecution.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestExecution.status": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestExecution.request"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RequestExecutionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RequestExecutionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RequestExecutionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestexecution.Table, requestexecution.Columns, sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestexecution.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(requestexecution.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(requestexecution.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestexecution.FieldResponseBody, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseBody(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseBody, value)
		})
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestexecution.FieldResponseBody, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseChunks(); ok {
		_spec.SetField(requestexecution.FieldResponseChunks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseChunks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseChunks, value)
		})
	}
	if _u.mutation.ResponseChunksCleared() {
		_spec.ClearField(requestexecution.FieldResponseChunks, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestexecution.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestexecution.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseStatusCode(); ok {
		_spec.SetField(requestexecution.FieldResponseStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseStatusCode(); ok {
		_spec.AddField(requestexecution.FieldResponseStatusCode, field.TypeInt, value)
	}
	if _u.mutation.ResponseStatusCodeCleared() {
		_spec.ClearField(requestexecution.FieldResponseStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestexecution.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MetricsLatencyMs(); ok {
		_spec.SetField(requestexecution.FieldMetricsLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricsLatencyMs(); ok {
		_spec.AddField(requestexecution.FieldMetricsLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.MetricsLatencyMsCleared() {
		_spec.ClearField(requestexecution.FieldMetricsLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.MetricsFirstTokenLatencyMs(); ok {
		_spec.SetField(requestexecution.FieldMetricsFirstTokenLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricsFirstTokenLatencyMs(); ok {
		_spec.AddField(requestexecution.FieldMetricsFirstTokenLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.MetricsFirstTokenLatencyMsCleared() {
		_spec.ClearField(requestexecution.FieldMetricsFirstTokenLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.MetricsReasoningDurationMs(); ok {
		_spec.SetField(requestexecution.FieldMetricsReasoningDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricsReasoningDurationMs(); ok {
		_spec.AddField(requestexecution.FieldMetricsReasoningDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.MetricsReasoningDurationMsCleared() {
		_spec.ClearField(requestexecution.FieldMetricsReasoningDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(requestexecution.FieldRequestHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldRequestHeaders, value)
		})
	}
	if _u.mutation.RequestHeadersCleared() {
		_spec.ClearField(requestexecution.FieldRequestHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequestURL(); ok {
		_spec.SetField(requestexecution.FieldRequestURL, field.TypeString, value)
	}
	if _u.mutation.RequestURLCleared() {
		_spec.ClearField(requestexecution.FieldRequestURL, field.TypeString)
	}
	if value, ok := _u.mutation.PassThroughApplied(); ok {
		_spec.SetField(requestexecution.FieldPassThroughApplied, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestExecutionUpdateOne is the builder for updating a single RequestExecution entity.
type RequestExecutionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RequestExecutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestExecutionUpdateOne) SetUpdatedAt(v time.Time) *RequestExecutionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *RequestExecutionUpdateOne) SetExternalID(v string) *RequestExecutionUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableExternalID(v *string) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *RequestExecutionUpdateOne) ClearExternalID() *RequestExecutionUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestExecutionUpdateOne) SetResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// AppendResponseBody appends value to the "response_body" field.
func (_u *RequestExecutionUpdateOne) AppendResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.AppendResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestExecutionUpdateOne) ClearResponseBody() *RequestExecutionUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseChunks sets the "response_chunks" field.
func (_u *RequestExecutionUpdateOne) SetResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.SetResponseChunks(v)
	return _u
}

// AppendResponseChunks appends value to the "response_chunks" field.
func (_u *RequestExecutionUpdateOne) AppendResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.AppendResponseChunks(v)
	return _u
}

// ClearResponseChunks clears the value of the "response_chunks" field.
func (_u *RequestExecutionUpdateOne) ClearResponseChunks() *RequestExecutionUpdateOne {
	_u.mutation.ClearResponseChunks()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestExecutionUpdateOne) SetErrorMessage(v string) *RequestExecutionUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableErrorMessage(v *string) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestExecutionUpdateOne) ClearErrorMessage() *RequestExecutionUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetResponseStatusCode sets the "response_status_code" field.
func (_u *RequestExecutionUpdateOne) SetResponseStatusCode(v int) *RequestExecutionUpdateOne {
	_u.mutation.ResetResponseStatusCode()
	_u.mutation.SetResponseStatusCode(v)
	return _u
}

// SetNillableResponseStatusCode sets the "response_status_code" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableResponseStatusCode(v *int) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetResponseStatusCode(*v)
	}
	return _u
}

// AddResponseStatusCode adds value to the "response_status_code" field.
func (_u *RequestExecutionUpdateOne) AddResponseStatusCode(v int) *RequestExecutionUpdateOne {
	_u.mutation.AddResponseStatusCode(v)
	return _u
}

// ClearResponseStatusCode clears the value of the "response_status_code" field.
func (_u *RequestExecutionUpdateOne) ClearResponseStatusCode() *RequestExecutionUpdateOne {
	_u.mutation.ClearResponseStatusCode()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestExecutionUpdateOne) SetStatus(v requestexecution.Status) *RequestExecutionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableStatus(v *requestexecution.Status) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetricsLatencyMs sets the "metrics_latency_ms" field.
func (_u *RequestExecutionUpdateOne) SetMetricsLatencyMs(v int64) *RequestExecutionUpdateOne {
	_u.mutation.ResetMetricsLatencyMs()
	_u.mutation.SetMetricsLatencyMs(v)
	return _u
}

// SetNillableMetricsLatencyMs sets the "metrics_latency_ms" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableMetricsLatencyMs(v *int64) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetMetricsLatencyMs(*v)
	}
	return _u
}

// AddMetricsLatencyMs adds value to the "metrics_latency_ms" field.
func (_u *RequestExecutionUpdateOne) AddMetricsLatencyMs(v int64) *RequestExecutionUpdateOne {
	_u.mutation.AddMetricsLatencyMs(v)
	return _u
}

// ClearMetricsLatencyMs clears the value of the "metrics_latency_ms" field.
func (_u *RequestExecutionUpdateOne) ClearMetricsLatencyMs() *RequestExecutionUpdateOne {
	_u.mutation.ClearMetricsLatencyMs()
	return _u
}

// SetMetricsFirstTokenLatencyMs sets the "metrics_first_token_latency_ms" field.
func (_u *RequestExecutionUpdateOne) SetMetricsFirstTokenLatencyMs(v int64) *RequestExecutionUpdateOne {
	_u.mutation.ResetMetricsFirstTokenLatencyMs()
	_u.mutation.SetMetricsFirstTokenLatencyMs(v)
	return _u
}

// SetNillableMetricsFirstTokenLatencyMs sets the "metrics_first_token_latency_ms" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableMetricsFirstTokenLatencyMs(v *int64) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetMetricsFirstTokenLatencyMs(*v)
	}
	return _u
}

// AddMetricsFirstTokenLatencyMs adds value to the "metrics_first_token_latency_ms" field.
func (_u *RequestExecutionUpdateOne) AddMetricsFirstTokenLatencyMs(v int64) *RequestExecutionUpdateOne {
	_u.mutation.AddMetricsFirstTokenLatencyMs(v)
	return _u
}

// ClearMetricsFirstTokenLatencyMs clears the value of the "metrics_first_token_latency_ms" field.
func (_u *RequestExecutionUpdateOne) ClearMetricsFirstTokenLatencyMs() *RequestExecutionUpdateOne {
	_u.mutation.ClearMetricsFirstTokenLatencyMs()
	return _u
}

// SetMetricsReasoningDurationMs sets the "metrics_reasoning_duration_ms" field.
func (_u *RequestExecutionUpdateOne) SetMetricsReasoningDurationMs(v int64) *RequestExecutionUpdateOne {
	_u.mutation.ResetMetricsReasoningDurationMs()
	_u.mutation.SetMetricsReasoningDurationMs(v)
	return _u
}

// SetNillableMetricsReasoningDurationMs sets the "metrics_reasoning_duration_ms" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableMetricsReasoningDurationMs(v *int64) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetMetricsReasoningDurationMs(*v)
	}
	return _u
}

// AddMetricsReasoningDurationMs adds value to the "metrics_reasoning_duration_ms" field.
func (_u *RequestExecutionUpdateOne) AddMetricsReasoningDurationMs(v int64) *RequestExecutionUpdateOne {
	_u.mutation.AddMetricsReasoningDurationMs(v)
	return _u
}

// ClearMetricsReasoningDurationMs clears the value of the "metrics_reasoning_duration_ms" field.
func (_u *RequestExecutionUpdateOne) ClearMetricsReasoningDurationMs() *RequestExecutionUpdateOne {
	_u.mutation.ClearMetricsReasoningDurationMs()
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *RequestExecutionUpdateOne) SetRequestHeaders(v objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// AppendRequestHeaders appends value to the "request_headers" field.
func (_u *RequestExecutionUpdateOne) AppendRequestHeaders(v objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.AppendRequestHeaders(v)
	return _u
}

// ClearRequestHeaders clears the value of the "request_headers" field.
func (_u *RequestExecutionUpdateOne) ClearRequestHeaders() *RequestExecutionUpdateOne {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// SetRequestURL sets the "request_url" field.
func (_u *RequestExecutionUpdateOne) SetRequestURL(v string) *RequestExecutionUpdateOne {
	_u.mutation.SetRequestURL(v)
	return _u
}

// SetNillableRequestURL sets the "request_url" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableRequestURL(v *string) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetRequestURL(*v)
	}
	return _u
}

// ClearRequestURL clears the value of the "request_url" field.
func (_u *RequestExecutionUpdateOne) ClearRequestURL() *RequestExecutionUpdateOne {
	_u.mutation.ClearRequestURL()
	return _u
}

// SetPassThroughApplied sets the "pass_through_applied" field.
func (_u *RequestExecutionUpdateOne) SetPassThroughApplied(v bool) *RequestExecutionUpdateOne {
	_u.mutation.SetPassThroughApplied(v)
	return _u
}

// SetNillablePassThroughApplied sets the "pass_through_applied" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillablePassThroughApplied(v *bool) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetPassThroughApplied(*v)
	}
	return _u
}

// Mutation returns the RequestExecutionMutation object of the builder.
func (_u *RequestExecutionUpdateOne) Mutation() *RequestExecutionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestExecutionUpdate builder.
func (_u *RequestExecutionUpdateOne) Where(ps ...predicate.RequestExecution) *RequestExecutionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestExecutionUpdateOne) Select(field string, fields ...string) *RequestExecutionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestExecution entity.
func (_u *RequestExecutionUpdateOne) Save(ctx context.Context) (*RequestExecution, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestExecutionUpdateOne) SaveX(ctx context.Context) *RequestExecution {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestExecutionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestExecutionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestExecutionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestexecution.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestExecutionUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := requestexecution.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "RequestExecution.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestExecution.status": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestExecution.request"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RequestExecutionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RequestExecutionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RequestExecutionUpdateOne) sqlSave(ctx context.Context) (_node *RequestExecution, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestexecution.Table, requestexecution.Columns, sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestExecution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestexecution.FieldID)
		for _, f := range fields {
			if !requestexecution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestexecution.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(requestexecution.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(requestexecution.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestexecution.FieldResponseBody, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseBody(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseBody, value)
		})
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestexecution.FieldResponseBody, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseChunks(); ok {
		_spec.SetField(requestexecution.FieldResponseChunks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseChunks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseChunks, value)
		})
	}
	if _u.mutation.ResponseChunksCleared() {
		_spec.ClearField(requestexecution.FieldResponseChunks, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestexecution.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestexecution.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseStatusCode(); ok {
		_spec.SetField(requestexecution.FieldResponseStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseStatusCode(); ok {
		_spec.AddField(requestexecution.FieldResponseStatusCode, field.TypeInt, value)
	}
	if _u.mutation.ResponseStatusCodeCleared() {
		_spec.ClearField(requestexecution.FieldResponseStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestexecution.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MetricsLatencyMs(); ok {
		_spec.SetField(requestexecution.FieldMetricsLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricsLatencyMs(); ok {
		_spec.AddField(requestexecution.FieldMetricsLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.MetricsLatencyMsCleared() {
		_spec.ClearField(requestexecution.FieldMetricsLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.MetricsFirstTokenLatencyMs(); ok {
		_spec.SetField(requestexecution.FieldMetricsFirstTokenLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricsFirstTokenLatencyMs(); ok {
		_spec.AddField(requestexecution.FieldMetricsFirstTokenLatencyMs, field.TypeInt64, value)
	}
	if _u.mutation.MetricsFirstTokenLatencyMsCleared() {
		_spec.ClearField(requestexecution.FieldMetricsFirstTokenLatencyMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.MetricsReasoningDurationMs(); ok {
		_spec.SetField(requestexecution.FieldMetricsReasoningDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricsReasoningDurationMs(); ok {
		_spec.AddField(requestexecution.FieldMetricsReasoningDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.MetricsReasoningDurationMsCleared() {
		_spec.ClearField(requestexecution.FieldMetricsReasoningDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(requestexecution.FieldRequestHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestHeaders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldRequestHeaders, value)
		})
	}
	if _u.mutation.RequestHeadersCleared() {
		_spec.ClearField(requestexecution.FieldRequestHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequestURL(); ok {
		_spec.SetField(requestexecution.FieldRequestURL, field.TypeString, value)
	}
	if _u.mutation.RequestURLCleared() {
		_spec.ClearField(requestexecution.FieldRequestURL, field.TypeString)
	}
	if value, ok := _u.mutation.PassThroughApplied(); ok {
		_spec.SetField(requestexecution.FieldPassThroughApplied, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RequestExecution{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
