// Code generated by ent, DO NOT EDIT.

package requestexecution

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldProjectID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldRequestID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldChannelID, v))
}

// DataStorageID applies equality check predicate on the "data_storage_id" field. It's identical to DataStorageIDEQ.
func DataStorageID(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldDataStorageID, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldExternalID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldModelID, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldFormat, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldErrorMessage, v))
}

// ResponseStatusCode applies equality check predicate on the "response_status_code" field. It's identical to ResponseStatusCodeEQ.
func ResponseStatusCode(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldResponseStatusCode, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldStream, v))
}

// MetricsLatencyMs applies equality check predicate on the "metrics_latency_ms" field. It's identical to MetricsLatencyMsEQ.
func MetricsLatencyMs(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldMetricsLatencyMs, v))
}

// MetricsFirstTokenLatencyMs applies equality check predicate on the "metrics_first_token_latency_ms" field. It's identical to MetricsFirstTokenLatencyMsEQ.
func MetricsFirstTokenLatencyMs(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldMetricsFirstTokenLatencyMs, v))
}

// MetricsReasoningDurationMs applies equality check predicate on the "metrics_reasoning_duration_ms" field. It's identical to MetricsReasoningDurationMsEQ.
func MetricsReasoningDurationMs(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldMetricsReasoningDurationMs, v))
}

// RequestURL applies equality check predicate on the "request_url" field. It's identical to RequestURLEQ.
func RequestURL(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldRequestURL, v))
}

// PassThroughApplied applies equality check predicate on the "pass_through_applied" field. It's identical to PassThroughAppliedEQ.
func PassThroughApplied(v bool) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldPassThroughApplied, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldProjectID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldRequestID, vs...))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldChannelID))
}

// DataStorageIDEQ applies the EQ predicate on the "data_storage_id" field.
func DataStorageIDEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldDataStorageID, v))
}

// DataStorageIDNEQ applies the NEQ predicate on the "data_storage_id" field.
func DataStorageIDNEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldDataStorageID, v))
}

// DataStorageIDIn applies the In predicate on the "data_storage_id" field.
func DataStorageIDIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldDataStorageID, vs...))
}

// DataStorageIDNotIn applies the NotIn predicate on the "data_storage_id" field.
func DataStorageIDNotIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldDataStorageID, vs...))
}

// DataStorageIDIsNil applies the IsNil predicate on the "data_storage_id" field.
func DataStorageIDIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldDataStorageID))
}

// DataStorageIDNotNil applies the NotNil predicate on the "data_storage_id" field.
func DataStorageIDNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldDataStorageID))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDIsNil applies the IsNil predicate on the "external_id" field.
func ExternalIDIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldExternalID))
}

// ExternalIDNotNil applies the NotNil predicate on the "external_id" field.
func ExternalIDNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldExternalID))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContainsFold(FieldExternalID, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContainsFold(FieldModelID, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContainsFold(FieldFormat, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldResponseBody))
}

// ResponseChunksIsNil applies the IsNil predicate on the "response_chunks" field.
func ResponseChunksIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldResponseChunks))
}

// ResponseChunksNotNil applies the NotNil predicate on the "response_chunks" field.
func ResponseChunksNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldResponseChunks))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ResponseStatusCodeEQ applies the EQ predicate on the "response_status_code" field.
func ResponseStatusCodeEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldResponseStatusCode, v))
}

// ResponseStatusCodeNEQ applies the NEQ predicate on the "response_status_code" field.
func ResponseStatusCodeNEQ(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldResponseStatusCode, v))
}

// ResponseStatusCodeIn applies the In predicate on the "response_status_code" field.
func ResponseStatusCodeIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldResponseStatusCode, vs...))
}

// ResponseStatusCodeNotIn applies the NotIn predicate on the "response_status_code" field.
func ResponseStatusCodeNotIn(vs ...int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldResponseStatusCode, vs...))
}

// ResponseStatusCodeGT applies the GT predicate on the "response_status_code" field.
func ResponseStatusCodeGT(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldResponseStatusCode, v))
}

// ResponseStatusCodeGTE applies the GTE predicate on the "response_status_code" field.
func ResponseStatusCodeGTE(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldResponseStatusCode, v))
}

// ResponseStatusCodeLT applies the LT predicate on the "response_status_code" field.
func ResponseStatusCodeLT(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldResponseStatusCode, v))
}

// ResponseStatusCodeLTE applies the LTE predicate on the "response_status_code" field.
func ResponseStatusCodeLTE(v int) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldResponseStatusCode, v))
}

// ResponseStatusCodeIsNil applies the IsNil predicate on the "response_status_code" field.
func ResponseStatusCodeIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldResponseStatusCode))
}

// ResponseStatusCodeNotNil applies the NotNil predicate on the "response_status_code" field.
func ResponseStatusCodeNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldResponseStatusCode))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldStatus, vs...))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldStream, v))
}

// MetricsLatencyMsEQ applies the EQ predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsEQ(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldMetricsLatencyMs, v))
}

// MetricsLatencyMsNEQ applies the NEQ predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsNEQ(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldMetricsLatencyMs, v))
}

// MetricsLatencyMsIn applies the In predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsIn(vs ...int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldMetricsLatencyMs, vs...))
}

// MetricsLatencyMsNotIn applies the NotIn predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsNotIn(vs ...int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldMetricsLatencyMs, vs...))
}

// MetricsLatencyMsGT applies the GT predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsGT(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldMetricsLatencyMs, v))
}

// MetricsLatencyMsGTE applies the GTE predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsGTE(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldMetricsLatencyMs, v))
}

// MetricsLatencyMsLT applies the LT predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsLT(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldMetricsLatencyMs, v))
}

// MetricsLatencyMsLTE applies the LTE predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsLTE(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldMetricsLatencyMs, v))
}

// MetricsLatencyMsIsNil applies the IsNil predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldMetricsLatencyMs))
}

// MetricsLatencyMsNotNil applies the NotNil predicate on the "metrics_latency_ms" field.
func MetricsLatencyMsNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldMetricsLatencyMs))
}

// MetricsFirstTokenLatencyMsEQ applies the EQ predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsEQ(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldMetricsFirstTokenLatencyMs, v))
}

// MetricsFirstTokenLatencyMsNEQ applies the NEQ predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsNEQ(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldMetricsFirstTokenLatencyMs, v))
}

// MetricsFirstTokenLatencyMsIn applies the In predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsIn(vs ...int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldMetricsFirstTokenLatencyMs, vs...))
}

// MetricsFirstTokenLatencyMsNotIn applies the NotIn predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsNotIn(vs ...int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldMetricsFirstTokenLatencyMs, vs...))
}

// MetricsFirstTokenLatencyMsGT applies the GT predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsGT(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldMetricsFirstTokenLatencyMs, v))
}

// MetricsFirstTokenLatencyMsGTE applies the GTE predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsGTE(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldMetricsFirstTokenLatencyMs, v))
}

// MetricsFirstTokenLatencyMsLT applies the LT predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsLT(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldMetricsFirstTokenLatencyMs, v))
}

// MetricsFirstTokenLatencyMsLTE applies the LTE predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsLTE(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldMetricsFirstTokenLatencyMs, v))
}

// MetricsFirstTokenLatencyMsIsNil applies the IsNil predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldMetricsFirstTokenLatencyMs))
}

// MetricsFirstTokenLatencyMsNotNil applies the NotNil predicate on the "metrics_first_token_latency_ms" field.
func MetricsFirstTokenLatencyMsNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldMetricsFirstTokenLatencyMs))
}

// MetricsReasoningDurationMsEQ applies the EQ predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsEQ(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldMetricsReasoningDurationMs, v))
}

// MetricsReasoningDurationMsNEQ applies the NEQ predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsNEQ(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldMetricsReasoningDurationMs, v))
}

// MetricsReasoningDurationMsIn applies the In predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsIn(vs ...int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldMetricsReasoningDurationMs, vs...))
}

// MetricsReasoningDurationMsNotIn applies the NotIn predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsNotIn(vs ...int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldMetricsReasoningDurationMs, vs...))
}

// MetricsReasoningDurationMsGT applies the GT predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsGT(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldMetricsReasoningDurationMs, v))
}

// MetricsReasoningDurationMsGTE applies the GTE predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsGTE(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldMetricsReasoningDurationMs, v))
}

// MetricsReasoningDurationMsLT applies the LT predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsLT(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldMetricsReasoningDurationMs, v))
}

// MetricsReasoningDurationMsLTE applies the LTE predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsLTE(v int64) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldMetricsReasoningDurationMs, v))
}

// MetricsReasoningDurationMsIsNil applies the IsNil predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldMetricsReasoningDurationMs))
}

// MetricsReasoningDurationMsNotNil applies the NotNil predicate on the "metrics_reasoning_duration_ms" field.
func MetricsReasoningDurationMsNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldMetricsReasoningDurationMs))
}

// RequestHeadersIsNil applies the IsNil predicate on the "request_headers" field.
func RequestHeadersIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldRequestHeaders))
}

// RequestHeadersNotNil applies the NotNil predicate on the "request_headers" field.
func RequestHeadersNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldRequestHeaders))
}

// RequestURLEQ applies the EQ predicate on the "request_url" field.
func RequestURLEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldRequestURL, v))
}

// RequestURLNEQ applies the NEQ predicate on the "request_url" field.
func RequestURLNEQ(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldRequestURL, v))
}

// RequestURLIn applies the In predicate on the "request_url" field.
func RequestURLIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIn(FieldRequestURL, vs...))
}

// RequestURLNotIn applies the NotIn predicate on the "request_url" field.
func RequestURLNotIn(vs ...string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotIn(FieldRequestURL, vs...))
}

// RequestURLGT applies the GT predicate on the "request_url" field.
func RequestURLGT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGT(FieldRequestURL, v))
}

// RequestURLGTE applies the GTE predicate on the "request_url" field.
func RequestURLGTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldGTE(FieldRequestURL, v))
}

// RequestURLLT applies the LT predicate on the "request_url" field.
func RequestURLLT(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLT(FieldRequestURL, v))
}

// RequestURLLTE applies the LTE predicate on the "request_url" field.
func RequestURLLTE(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldLTE(FieldRequestURL, v))
}

// RequestURLContains applies the Contains predicate on the "request_url" field.
func RequestURLContains(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContains(FieldRequestURL, v))
}

// RequestURLHasPrefix applies the HasPrefix predicate on the "request_url" field.
func RequestURLHasPrefix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasPrefix(FieldRequestURL, v))
}

// RequestURLHasSuffix applies the HasSuffix predicate on the "request_url" field.
func RequestURLHasSuffix(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldHasSuffix(FieldRequestURL, v))
}

// RequestURLIsNil applies the IsNil predicate on the "request_url" field.
func RequestURLIsNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldIsNull(FieldRequestURL))
}

// RequestURLNotNil applies the NotNil predicate on the "request_url" field.
func RequestURLNotNil() predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNotNull(FieldRequestURL))
}

// RequestURLEqualFold applies the EqualFold predicate on the "request_url" field.
func RequestURLEqualFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEqualFold(FieldRequestURL, v))
}

// RequestURLContainsFold applies the ContainsFold predicate on the "request_url" field.
func RequestURLContainsFold(v string) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldContainsFold(FieldRequestURL, v))
}

// PassThroughAppliedEQ applies the EQ predicate on the "pass_through_applied" field.
func PassThroughAppliedEQ(v bool) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldEQ(FieldPassThroughApplied, v))
}

// PassThroughAppliedNEQ applies the NEQ predicate on the "pass_through_applied" field.
func PassThroughAppliedNEQ(v bool) predicate.RequestExecution {
	return predicate.RequestExecution(sql.FieldNEQ(FieldPassThroughApplied, v))
}

// HasRequest applies the HasEdge predicate on the "request" edge.
func HasRequest() predicate.RequestExecution {
	return predicate.RequestExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RequestTable, RequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestWith applies the HasEdge predicate on the "request" edge with a given conditions (other predicates).
func HasRequestWith(preds ...predicate.Request) predicate.RequestExecution {
	return predicate.RequestExecution(func(s *sql.Selector) {
		step := newRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.RequestExecution {
	return predicate.RequestExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.RequestExecution {
	return predicate.RequestExecution(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDataStorage applies the HasEdge predicate on the "data_storage" edge.
func HasDataStorage() predicate.RequestExecution {
	return predicate.RequestExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DataStorageTable, DataStorageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDataStorageWith applies the HasEdge predicate on the "data_storage" edge with a given conditions (other predicates).
func HasDataStorageWith(preds ...predicate.DataStorage) predicate.RequestExecution {
	return predicate.RequestExecution(func(s *sql.Selector) {
		step := newDataStorageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestExecution) predicate.RequestExecution {
	return predicate.RequestExecution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestExecution) predicate.RequestExecution {
	return predicate.RequestExecution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestExecution) predicate.RequestExecution {
	return predicate.RequestExecution(sql.NotPredicates(p))
}
