// Code generated by ent, DO NOT EDIT.

package relaysitebalancesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// RelaySiteID applies equality check predicate on the "relay_site_id" field. It's identical to RelaySiteIDEQ.
func RelaySiteID(v int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldRelaySiteID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldBalance, v))
}

// Unit applies equality check predicate on the "unit" field. It's identical to UnitEQ.
func Unit(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldUnit, v))
}

// PulledAt applies equality check predicate on the "pulled_at" field. It's identical to PulledAtEQ.
func PulledAt(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldPulledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLTE(FieldUpdatedAt, v))
}

// RelaySiteIDEQ applies the EQ predicate on the "relay_site_id" field.
func RelaySiteIDEQ(v int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldRelaySiteID, v))
}

// RelaySiteIDNEQ applies the NEQ predicate on the "relay_site_id" field.
func RelaySiteIDNEQ(v int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNEQ(FieldRelaySiteID, v))
}

// RelaySiteIDIn applies the In predicate on the "relay_site_id" field.
func RelaySiteIDIn(vs ...int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldIn(FieldRelaySiteID, vs...))
}

// RelaySiteIDNotIn applies the NotIn predicate on the "relay_site_id" field.
func RelaySiteIDNotIn(vs ...int) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNotIn(FieldRelaySiteID, vs...))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLTE(FieldBalance, v))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNotIn(FieldUnit, vs...))
}

// UnitGT applies the GT predicate on the "unit" field.
func UnitGT(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGT(FieldUnit, v))
}

// UnitGTE applies the GTE predicate on the "unit" field.
func UnitGTE(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGTE(FieldUnit, v))
}

// UnitLT applies the LT predicate on the "unit" field.
func UnitLT(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLT(FieldUnit, v))
}

// UnitLTE applies the LTE predicate on the "unit" field.
func UnitLTE(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLTE(FieldUnit, v))
}

// UnitContains applies the Contains predicate on the "unit" field.
func UnitContains(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldContains(FieldUnit, v))
}

// UnitHasPrefix applies the HasPrefix predicate on the "unit" field.
func UnitHasPrefix(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldHasPrefix(FieldUnit, v))
}

// UnitHasSuffix applies the HasSuffix predicate on the "unit" field.
func UnitHasSuffix(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldHasSuffix(FieldUnit, v))
}

// UnitEqualFold applies the EqualFold predicate on the "unit" field.
func UnitEqualFold(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEqualFold(FieldUnit, v))
}

// UnitContainsFold applies the ContainsFold predicate on the "unit" field.
func UnitContainsFold(v string) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldContainsFold(FieldUnit, v))
}

// PulledAtEQ applies the EQ predicate on the "pulled_at" field.
func PulledAtEQ(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldEQ(FieldPulledAt, v))
}

// PulledAtNEQ applies the NEQ predicate on the "pulled_at" field.
func PulledAtNEQ(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNEQ(FieldPulledAt, v))
}

// PulledAtIn applies the In predicate on the "pulled_at" field.
func PulledAtIn(vs ...time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldIn(FieldPulledAt, vs...))
}

// PulledAtNotIn applies the NotIn predicate on the "pulled_at" field.
func PulledAtNotIn(vs ...time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldNotIn(FieldPulledAt, vs...))
}

// PulledAtGT applies the GT predicate on the "pulled_at" field.
func PulledAtGT(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGT(FieldPulledAt, v))
}

// PulledAtGTE applies the GTE predicate on the "pulled_at" field.
func PulledAtGTE(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldGTE(FieldPulledAt, v))
}

// PulledAtLT applies the LT predicate on the "pulled_at" field.
func PulledAtLT(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLT(FieldPulledAt, v))
}

// PulledAtLTE applies the LTE predicate on the "pulled_at" field.
func PulledAtLTE(v time.Time) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.FieldLTE(FieldPulledAt, v))
}

// HasRelaySite applies the HasEdge predicate on the "relay_site" edge.
func HasRelaySite() predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RelaySiteTable, RelaySiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelaySiteWith applies the HasEdge predicate on the "relay_site" edge with a given conditions (other predicates).
func HasRelaySiteWith(preds ...predicate.RelaySite) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(func(s *sql.Selector) {
		step := newRelaySiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelaySiteBalanceSnapshot) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelaySiteBalanceSnapshot) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelaySiteBalanceSnapshot) predicate.RelaySiteBalanceSnapshot {
	return predicate.RelaySiteBalanceSnapshot(sql.NotPredicates(p))
}
